import { SHARED_PAGE_CONSTANTS } from '../shared/pages';

export const CONNECTIVITY_CONSTANTS = {
  RETRY: SHARED_PAGE_CONSTANTS.RETRY,
  COOLDOWN: SHARED_PAGE_CONSTANTS.COOLDOWN,
  COLORS: SHARED_PAGE_CONSTANTS.COLORS,
  MESSAGES: {
    RETRYING: SHARED_PAGE_CONSTANTS.MESSAGES.RETRYING,
    ERROR_COOLDOWN: SHARED_PAGE_CONSTANTS.MESSAGES.ERROR_COOLDOWN,
    ERROR_RETRYING: SHARED_PAGE_CONSTANTS.MESSAGES.ERROR_RETRYING,
    ERROR_RETRYING_COOLDOWN: SHARED_PAGE_CONSTANTS.MESSAGES.ERROR_RETRYING_COOLDOWN,
    COOLDOWN_TITLE: SHARED_PAGE_CONSTANTS.MESSAGES.COOLDOWN_TITLE,
    COOLDOWN_DESCRIPTION: SHARED_PAGE_CONSTANTS.MESSAGES.COOLDOWN_DESCRIPTION,
    ATTEMPT_COUNT: SHARED_PAGE_CONSTANTS.MESSAGES.ATTEMPT_COUNT,
    NEXT_RETRY: SHARED_PAGE_CONSTANTS.MESSAGES.NEXT_RETRY,
    CANCEL: SHARED_PAGE_CONSTANTS.MESSAGES.CANCEL,
    REFRESH: SHARED_PAGE_CONSTANTS.MESSAGES.REFRESH,
    CONNECTION_PROBLEM: SHARED_PAGE_CONSTANTS.MESSAGES.CONNECTION_PROBLEM,
  },
  LAYOUT: {
    ERROR_CONTAINER: SHARED_PAGE_CONSTANTS.LAYOUT.ERROR_CONTAINER,
    ERROR_CONTENT: SHARED_PAGE_CONSTANTS.LAYOUT.ERROR_CONTENT,
    PROGRESS_BAR_CONTAINER: SHARED_PAGE_CONSTANTS.LAYOUT.PROGRESS_BAR_CONTAINER,
    PROGRESS_BAR_FILL: SHARED_PAGE_CONSTANTS.LAYOUT.PROGRESS_BAR_FILL,
  },
} as const;

