export const INSIGHTS_UI = {
  ANALYZE_BUTTON: 'Analyze',
  ANALYZING: 'Analyzing… ({trigger})',
  QUEUED: 'Queued',
  CONFIDENCE: 'Confidence',
  RUN_LINE: 'Last run {status} · {model} · {steps} · {toolCalls}',
  RUN_LINE_RULES_ONLY: '{model} · rules only · {reads}',
  RUN_STEPS: { one: '{count} step', other: '{count} steps' },
  RUN_TOOL_CALLS: { one: '{count} tool call', other: '{count} tool calls' },
  RUN_READS: { one: '{count} read', other: '{count} reads' },
  RUNTIME_BANNER_ABSENT: 'The model runtime is not installed.',
  RUNTIME_BANNER_UNREACHABLE: 'The model runtime is unreachable.',
  RUNTIME_BANNER_MODEL_MISSING: 'The analyzer model is not installed.',
  RUNTIME_BANNER_PULLING: 'The analyzer model is being installed.',
  RUNTIME_BANNER_UNSUPPORTED: 'The configured model cannot use tools.',
  RUNTIME_BANNER_RULES_ONLY: 'Insights use detection rules only until the model is ready.',
  NOT_ANALYZED_YET: 'Not analyzed yet',
  SETUP_REVIEWED: 'Setup reviewed',
  NOT_REVIEWED_YET: 'Not reviewed yet',
  WHY: 'Why',
  WHAT_TO_DO: 'What to do',
  DETAILS: 'Details',
  MESSAGE: 'Message',
  EVIDENCE: 'Evidence',
  FIRST_SEEN: 'First seen',
  LAST_SEEN: 'Last seen',
  RUNS: 'Runs',
  ACKNOWLEDGE: 'Acknowledge',
  ACKNOWLEDGED: 'Acknowledged',
  DISMISS: 'Dismiss',
  DISMISSED: 'Dismissed',
  REOPEN: 'Reopen',
  RUN_STATUS: {
    QUEUED: 'queued',
    RUNNING: 'running',
    DONE: 'done',
    FAILED: 'failed',
  },
  TRIGGER: {
    MANUAL: 'manual',
    INCIDENT: 'incident',
    RECOVERY: 'recovery',
  },
  SEVERITY: {
    INFO: 'Info',
    WARNING: 'Warning',
    CRITICAL: 'Critical',
  },
  CONFIDENCE_LEVEL: {
    LOW: 'Low',
    MEDIUM: 'Medium',
    HIGH: 'High',
  },
  KIND: {
    CRASHLOOP: 'Crash loop',
    OOM: 'Out of memory',
    IMAGE_PULL: 'Image pull',
    PROBE_FAILURE: 'Probe failure',
    SCHEDULING: 'Scheduling',
    ROLLOUT_STUCK: 'Rollout stuck',
    CONFIG_CHANGE_REGRESSION: 'Config change regression',
    RESOURCE_PRESSURE: 'Resource pressure',
    OTHER: 'Other',
    RELIABILITY: 'Reliability',
    RESOURCES: 'Resources',
    SCALING: 'Scaling',
    SECURITY: 'Security',
    IMAGES: 'Images',
    CONFIG: 'Configuration',
    NETWORKING: 'Networking',
    CHANGE_RISK: 'Change risk',
    PROTECTION: 'Protection',
    CONSISTENCY: 'Consistency',
  },
  ERRORS: {
    ANALYZER_DISABLED: 'The local analyzer is disabled.',
    RUNTIME_PULLING: 'The analyzer model is still being installed.',
    COOLDOWN_ACTIVE: 'An analysis ran moments ago. Try again in a minute.',
    QUEUE_FULL: 'The analyzer queue is full. Try again later.',
    MODEL_TIMEOUT: 'The model took too long to answer.',
    CONTEXT_OVERFLOW: 'The investigation outgrew the model context.',
    INVALID_TOOL_CALLS: 'The model made repeated invalid tool calls.',
    INVALID_OUTPUT: 'The model returned findings in an invalid format.',
    BUSY: 'The analyzer is busy. Try again shortly.',
    APP_NOT_FOUND: 'The application no longer exists.',
    STORAGE_UNAVAILABLE: 'Insight storage is unavailable.',
    JOB_EXPIRED: 'The analysis waited too long and was dropped.',
    RUN_IN_PROGRESS: 'Another analysis was already running.',
    JOB_DROPPED: 'The analysis was skipped because automatic analysis is off or cooling down.',
    INTERNAL_ERROR: 'The analyzer hit an internal error.',
    INSIGHT_NOT_FOUND: 'This insight no longer exists.',
    INVALID_TRIAGE: 'This insight cannot take that action in its current state.',
    INVALID_REQUEST: 'The request was not valid.',
    INVALID_APP: 'The application name is not valid.',
    AUTO_PULL_DISABLED:
      'Automatic model installation is off. Install the model on the runtime, then check it again.',
    TRIAGE_FAILED: 'The action failed.',
  },
  PANEL: {
    PREVIOUS: 'Previous (↑ or k)',
    NEXT: 'Next (↓ or j)',
    TITLE_INCIDENT: 'Incident',
    TITLE_RECOMMENDATION: 'Recommendation',
    POSITION: '{index} of {total}',
    APPLICATION: 'Application',
    NAMESPACE: 'Namespace',
    WORKLOAD: 'Workload',
    RESOLVED: 'Resolved',
    ANALYSIS: 'Analysis',
    OTHER_FINDINGS: 'Other findings for this app ({count})',
    NOT_FOUND: 'This insight no longer exists.',
    LOAD_FAILED: 'This insight could not be loaded. Try again shortly.',
    COPY: 'Copy',
    COPIED: 'Copied',
  },
  PAGE: {
    TITLE: 'Insights',
    SUBTITLE:
      'Why an application broke, with the evidence and the change it followed, and what to fix in its setup.',
    SEARCH_PLACEHOLDER: 'Search by application, namespace, subject or title',
    SEARCH_BUTTON: 'Search',
    REFRESH: 'Refresh',
    INCIDENTS_SUFFIX: { one: 'incident', other: 'incidents' },
    RECOMMENDATIONS_SUFFIX: { one: 'recommendation', other: 'recommendations' },
    NO_MATCH: 'No insights match these filters.',
    CAPPED: 'Showing the {shown} most severe of {total}. Narrow the filters to see the rest.',
    ALL_CLEAR_TITLE: 'All clear',
    ALL_CLEAR_INCIDENTS: 'No open incidents.',
    ALL_CLEAR_RECOMMENDATIONS: 'No open recommendations.',
    CHECKED: 'Checked',
    MANUAL_ANALYSIS_TITLE: 'Automatic analysis is off',
    MANUAL_ANALYSIS: 'Run Analyze on an application to explain what went wrong.',
    ANALYZER_OFF_TITLE: 'Insights are off',
    ANALYZER_OFF:
      'Turn them on in Settings to explain incidents and review each application’s setup. Existing findings stay listed.',
    OPEN_SETTINGS: 'Open Insights settings',
    GROUP_BY: 'Group by',
    SEVERITY_FILTER: 'Filter by severity',
    ALL: 'All',
    APP_CHIP: 'Application',
    SELECT: 'Select',
    SELECT_ACTIVE: 'Done',
    SELECT_PAGE: 'Select page',
    BULK_ACKNOWLEDGE: 'Acknowledge',
    BULK_DISMISS: 'Dismiss',
    BULK_REOPEN: 'Reopen',
    BULK_DONE: '{done} updated',
    BULK_SKIPPED: '{skipped} skipped: the action does not apply to them',
    BULK_FAILED: '{failed} failed',
    BULK_NOT_ALLOWED: 'Needs the Owner level on insights and permission to triage.',
    GROUP_TOTAL: { one: '{count} finding', other: '{count} findings' },
    GROUP_NAMESPACES_SEPARATOR: ', ',
    GROUP: {
      NONE: 'None',
      APP: 'Application',
      NAMESPACE: 'Namespace',
      CATEGORY: 'Category',
    },
    TABS: {
      INCIDENTS: 'Incidents',
      RECOMMENDATIONS: 'Recommendations',
      COUNT: '{label} ({count})',
    },
    COLUMNS: {
      SEVERITY: 'Severity',
      TITLE: 'Insight',
      APPLICATION: 'Application',
      NAMESPACE: 'Namespace',
      KIND: 'Kind',
      FAMILY: 'Family',
      STATE: 'State',
      TRIAGE: 'Triage',
      ENVIRONMENT: 'Environment',
      LAST_SEEN: 'Last seen',
    },
    STATE: {
      OPEN: 'Open',
      UPDATED: 'Updated',
      RESOLVED: 'Resolved',
      STALE: 'Stale',
    },
    TRIAGE: {
      DEFAULT: 'Not dismissed',
      UNTRIAGED: 'Untriaged',
      ACKNOWLEDGED: 'Acknowledged',
      DISMISSED: 'Dismissed',
      ALL: 'All',
    },
    FILTER: {
      BY_KIND: 'Kind',
      BY_FAMILY: 'Family',
      BY_SEVERITY: 'Severity',
      BY_STATE: 'State',
      BY_TRIAGE: 'Triage',
      BY_NAMESPACE: 'Namespaces',
      BY_ENVIRONMENT: 'Environment',
      ANY: 'Any',
    },
  },
} as const;
