export const GROUPS_CONSTANTS = {
  LABELS: {
    HEADER_TITLE: 'Groups',
    HEADER_SUBTITLE: 'Manage existing groups',
    VIEW_SUBTITLE: 'View group details',
    EDIT_SUBTITLE: 'Edit group details',
    CREATE_SUBTITLE: 'Create a new group',
    NOT_FOUND: 'Group not found',
    UPDATE_BUTTON: 'Update Group',
    CREATE_BUTTON_TEXT: 'Add New Group',
    BREADCRUMBS: {
      GROUPS: 'Groups',
      EDIT: 'Edit',
      CREATE: 'Add New Group',
      CATEGORIES: 'Categories',
    },
    MESSAGES: {
      CREATED: (name: string) => `Group "${name}" created`,
      UPDATED: (name: string) => `Group "${name}" updated`,
      DELETED: 'Group deleted successfully',
      CREATE_FAILED: 'Failed to create group',
      UPDATE_FAILED: 'Failed to update group',
      DELETE_FAILED: 'Failed to delete group',
      NO_GROUPS_TITLE: 'No groups yet',
      NO_GROUPS_DESCRIPTION:
        'Get started by creating your first group. Groups help you organize and manage users with similar roles and permissions.',
      LOADING_ROLES: 'Loading roles...',
      NO_ROLES_AVAILABLE: 'No roles available',
      NO_ASSIGNED_ROLES: 'No roles assigned yet',
      ROLE_DEASSIGNED: (roleName: string) => `Role "${roleName}" was removed from group`,
      ROLE_DEASSIGN_FAILED: 'Failed to remove role from group',
      LOADING_MEMBERS: 'Loading members...',
      NO_MEMBERS_AVAILABLE: 'No members available',
      NO_ASSIGNED_MEMBERS: 'No members assigned yet',
      MEMBER_DEASSIGNED: (memberName: string) => `Member "${memberName}" was removed from group`,
      MEMBER_DEASSIGN_FAILED: 'Failed to remove member from group',
      MEMBERS_UPDATED: (groupName: string) => `Members for "${groupName}" updated`,
      MEMBERS_UPDATE_FAILED: 'Failed to update group members',
    },
    COLUMNS: {
      NAME: 'Group Name',
      DESCRIPTION: 'Description',
      CATEGORY: 'Category',
      CREATED: 'Creation Date',
      LAST_UPDATE: 'Last Updated',
      CREATED_BY: 'Created By',
      LAST_UPDATED_BY: 'Last Updated By',
      MEMBERS: 'Members',
    },
    ACTIONS: {
      VIEW: 'View',
      EDIT: 'Edit',
      EDIT_DISABLED_TOOLTIP: 'You do not have permission to edit groups',
      DELETE: 'Delete',
      DELETE_DISABLED_TOOLTIP: 'You do not have permission to delete groups',
      CREATE_DISABLED_TOOLTIP: 'You do not have permission to create groups',
      ATTACH_ROLE_DISABLED_TOOLTIP: 'You do not have permission to attach roles',
      REMOVE_MEMBER_DISABLED_TOOLTIP: 'You do not have permission to remove members',
      MANAGE_ROLES_DISABLED_TOOLTIP: 'You do not have permission to manage roles',
      MANAGE_MEMBERS_DISABLED_TOOLTIP: 'You do not have permission to manage members',
      BULK_DELETE: 'Bulk Delete',
      ATTACH_ROLE: 'Attach Role',
      MANAGE_ROLES: 'Manage Roles',
      MANAGE_MEMBERS: 'Manage Members',
      DELETE_MODAL_TITLE: 'Delete Group',
      DELETE_MODAL_CONTENT: (name: string) => `Are you sure you want to delete "${name}"?`,
      BULK_DELETE_MODAL_TITLE: 'Delete Groups',
      BULK_DELETE_MODAL_CONTENT: (count: number) =>
        `Are you sure you want to delete ${count} group${count > 1 ? 's' : ''}? This action cannot be undone.`,
      DELETE_MODAL_OK: 'Delete',
      BULK_DELETE_LOADING: (count: number) => `Deleting ${count} group${count > 1 ? 's' : ''}...`,
      BULK_DELETE_SUCCESS: (count: number) =>
        `${count} group${count > 1 ? 's' : ''} deleted successfully`,
      BULK_DELETE_FAILED: 'Failed to delete some groups',
      DEASSIGN_ROLE_MODAL_TITLE: 'Remove Role',
      DEASSIGN_ROLE_MODAL_ACTION: 'Remove',
      DEASSIGN_ROLE_MODAL_CONFIRM: 'Remove',
      DEASSIGN_ROLE_RESOURCE_TYPE: 'role',
      DEASSIGN_MEMBER_MODAL_TITLE: 'Remove Member',
      DEASSIGN_MEMBER_MODAL_ACTION: 'Remove',
      DEASSIGN_MEMBER_MODAL_CONFIRM: 'Remove',
      DEASSIGN_MEMBER_RESOURCE_TYPE: 'member',
    },
    FORM: {
      TITLE: 'Add New Group',
      SUBTITLE: 'Add a new group',
      SECTION_TITLE: 'Group Details',
      SECTION_SUBTITLE: 'Provide the group information.',
      BUTTON_TEXT: 'Add New Group',
      SECTIONS: {
        BASIC_DETAILS: 'Basic Details',
        MEMBERS: 'Members',
      },
      FIELDS: {
        NAME_LABEL: 'Group Name',
        NAME_PLACEHOLDER: 'e.g. Development Team',
        DESCRIPTION_LABEL: 'Description',
        DESCRIPTION_PLACEHOLDER: 'e.g. Group for development team members',
        CATEGORY_LABEL: 'Category',
        CATEGORY_PLACEHOLDER: 'Select a category',
        ASSIGNED_USERS_LABEL: 'Assigned Users',
        NAME_VALIDATION: {
          MIN_LENGTH: 1,
          MAX_LENGTH: 100,
          DUPLICATE_ERROR: 'A group with this name already exists',
          INVALID_CHARS_ERROR:
            'Group name can only contain letters, numbers, hyphens (-), and underscores (_)',
          LENGTH_ERROR: (min: number, max: number) =>
            `Group name must be between ${min} and ${max} characters`,
        },
      },
    },
    PANELS: {
      VIEW: {
        TITLE: 'Group Details',
      },
      EDIT: {
        TITLE: 'Edit Group',
      },
      ATTACH_ROLES: {
        TITLE: 'Manage Roles',
        SUBTITLE: (groupName: string) => `View and manage roles for ${groupName}`,
        SUBMIT_BUTTON: 'Update roles',
        SEARCH_PLACEHOLDER: 'Search roles by name, type, status, or validity...',
        SHOW_ASSIGNED_BUTTON: 'Assigned',
        SHOW_ASSIGNED_TOOLTIP: 'View all roles currently assigned to this group',
      },
      ASSIGN_MEMBERS: {
        TITLE: 'Manage Members',
        SUBTITLE: (groupName: string) => `View and manage members for ${groupName}`,
        SUBMIT_BUTTON: 'Update members',
        SEARCH_PLACEHOLDER: 'Search members by username or email...',
        SHOW_ASSIGNED_BUTTON: 'Assigned',
        SHOW_ASSIGNED_TOOLTIP: 'View all members currently assigned to this group',
      },
    },
    VIEW_LABELS: {
      NAME: 'Name',
      DESCRIPTION: 'Description',
      CATEGORY: 'Category',
      CREATION_DATE: 'Creation Date',
      LAST_UPDATE: 'Last Update',
      CREATED_BY: 'Created By',
      LAST_UPDATED_BY: 'Last Updated By',
    },
    FILTER: {
      LABELS: {
        BY_CREATION_DATE: 'BY CREATION DATE',
        BY_TYPE: 'BY TYPE',
        BY_CATEGORY: 'BY CATEGORY',
        BY_VALIDITY: 'BY VALIDITY',
        BY_STATUS: 'BY STATUS',
        FROM: 'From',
        TO: 'To',
      },
      OPTIONS: {
        ALL: 'All',
        BUILT_IN: 'Built-in',
        CUSTOM: 'Custom',
        PERMANENT: 'Permanent',
        TEMPORARY: 'Temporary',
        SESSION_BASED: 'Session-based',
        ACTIVE: 'Active',
        INACTIVE: 'Inactive',
      },
    },
    TOOLBAR: {
      SEARCH: {
        PLACEHOLDER: 'Search groups',
        BUTTON_LABEL: 'Search',
      },
      FILTER: {
        BUTTON_LABEL: 'Filter',
      },
      MANAGE: {
        BUTTON_LABEL: 'Manage',
      },
    },
    EMPTY: {
      NO_GROUPS_FOUND: 'No Groups Found',
      NO_CATEGORIES_FOUND: 'No categories found',
    },
    PAGINATION: {
      SHOW_ROWS: 'Show rows',
    },
    LOGS: {
      EDIT_CATEGORY: (category: unknown) => `Edit category: ${JSON.stringify(category)}`,
      DELETE_CATEGORY: (category: unknown) => `Delete category: ${JSON.stringify(category)}`,
    },
    MODAL: {
      CANCEL: 'Cancel',
    },
  },
  KEYS: {
    NAME: 'name',
    DESCRIPTION: 'description',
    CATEGORY: 'categoryID',
    CREATED_AT: 'creationDate',
    LAST_UPDATE: 'lastUpdateDate',
    CREATED_BY: 'createdBy',
    LAST_UPDATED_BY: 'lastUpdatedBy',
    MEMBERS: 'assignedUsersIDs',
    ACTIONS: 'actions',
  } as const,
  SIZES: {
    ROW_HEIGHT: 32,
    HEADER_ICON: 14,
    CHIP_FONT: 12,
    COLUMNS: {
      NAME: 150,
      DESCRIPTION: 150,
      CATEGORY: 130,
      CREATED: 150,
      LAST_UPDATE: 140,
      CREATED_BY: 140,
      LAST_UPDATED_BY: 140,
      MEMBERS: 110,
      ACTIONS: 70,
    },
    MODAL_WIDTH: 360,
  },
  ERROR_MESSAGES: {
    CLIENT: {
      FETCH_GROUPS_FAILED: '[APIClient] Failed to fetch groups:',
      FETCH_GROUP_DETAILS_FAILED: (id: string) =>
        `[APIClient] Failed to fetch group details for ${id}:`,
      CREATE_GROUP_FAILED: (name: string) => `[APIClient] Failed to create group: ${name}`,
      UPDATE_GROUP_FAILED: (id: string) => `[APIClient] Failed to update group: ${id}`,
      DELETE_GROUP_FAILED: (id: string) => `[APIClient] Failed to delete group: ${id}`,
      DELETE_GROUP_MISSING_ID: '[APIClient] Cannot delete group: missing id',
    },
  },
} as const;

export const GROUPS_ERROR_MESSAGES = GROUPS_CONSTANTS.ERROR_MESSAGES;
