import { COMMON_VALUES } from '../shared/common';

export const STORAGE_KEYS = {
  HAS_CLUSTER_INSIGHTS: 'HAS_CLUSTER_INSIGHTS',
  WELCOME_PENDING: 'WELCOME_PENDING',
  RESOURCE_ACTIVE_TAB: 'RESOURCE_ACTIVE_TAB',
  SESSION_TOKEN: 'SESSION_TOKEN',
  CURRENT_USER: 'CURRENT_USER',
} as const;

export const STORE_ACTIONS = {
  INSIGHTS: {
    CHECK_CLUSTER: 'insights/checkCluster',
  },
  GROUPERS: {
    FETCH: 'groupers/fetch',
    FETCH_SILENT: 'groupers/fetchSilent',
    TRIGGER_GROUPER_SYNC: 'groupers/triggerSync',
    REFRESH_AUTO_GROUPERS: 'groupers/refreshAuto',
    FETCH_DETAILS: 'groupers/fetchDetails',
  },
  APPLICATIONS: {
    FETCH: 'applications/fetch',
    FETCH_SILENT: 'applications/fetchSilent',
    FETCH_DETAILS: 'applications/fetchDetails',
    FETCH_SNAPSHOTS: 'applications/fetchSnapshots',
    FETCH_SNAPSHOT_MANIFEST: 'applications/fetchSnapshotManifest',
    UPDATE: 'applications/update',
    DELETE: 'applications/delete',
    TRIGGER_ROLLBACK: 'applications/triggerRollback',
  },
  GROUPER: {
    UPDATE_SYNC: 'grouper/updateGrouperSync',
    CHECK_MAINTENANCE: 'grouper/checkMaintenanceMode',
    ENABLE_MAINTENANCE: 'grouper/enableMaintenanceMode',
    UPDATE_MAINTENANCE: 'grouper/updateMaintenanceMode',
    REMOVE_MAINTENANCE: 'grouper/removeMaintenanceMode',
  },
  WORKLOADS: {
    FETCH_APPS: 'workloads/fetchApps',
    FETCH_BATCHES: 'workloads/fetchBatches',
    FETCH_APP_DETAILS: 'workloads/fetchAppDetails',
    UPDATE_APP_SYNC: 'workloads/updateAppSync',
    TRIGGER_GROUPER_SYNC: 'workloads/triggerSync',
    REFRESH_AUTO_GROUPERS: 'workloads/refreshAuto',
  },
  BRIDGES: {
    FETCH: 'bridges/fetch',
    FETCH_SILENT: 'bridges/fetchSilent',
    TRIGGER_BRIDGE_SYNC: 'bridges/triggerSync',
    REFRESH_AUTO_BRIDGES: 'bridges/refreshAuto',
    FETCH_DETAILS: 'bridges/fetchDetails',
  },
  BRIDGE: {
    UPDATE_SYNC: 'bridge/updateBridgeSync',
  },
  USERS: {
    FETCH: 'users/fetch',
    FETCH_SILENT: 'users/fetchSilent',
    FETCH_DETAILS: 'users/fetchDetails',
    CREATE: 'users/create',
    UPDATE: 'users/update',
    DELETE: 'users/delete',
  },
  GROUPS: {
    FETCH: 'groups/fetch',
    FETCH_SILENT: 'groups/fetchSilent',
    FETCH_DETAILS: 'groups/fetchDetails',
    CREATE: 'groups/create',
    UPDATE: 'groups/update',
    DELETE: 'groups/delete',
  },
  ROLES: {
    FETCH: 'roles/fetch',
    FETCH_SILENT: 'roles/fetchSilent',
    FETCH_DETAILS: 'roles/fetchDetails',
    CREATE: 'roles/create',
    UPDATE: 'roles/update',
    DELETE: 'roles/delete',
  },
  CATEGORIES: {
    FETCH_BY_SCOPE: 'categories/fetchByScope',
    FETCH_BY_SCOPE_SILENT: 'categories/fetchByScopeSilent',
  },
  PASSKEYS: {
    FETCH: 'passkeys/fetch',
    FETCH_SILENT: 'passkeys/fetchSilent',
    FETCH_DETAILS: 'passkeys/fetchDetails',
    CREATE: 'passkeys/create',
    UPDATE: 'passkeys/update',
    DELETE: 'passkeys/delete',
  },
} as const;

export const SYNC_MODES = COMMON_VALUES.SYNC_MODES;

export const STORE_ERRORS = {
  FETCH_GROUPERS: 'Failed to fetch groupers',
  FETCH_APPLICATIONS: 'Failed to fetch applications',
  TRIGGER_GROUPER_SYNC: 'Failed to trigger groupers sync',
  REFRESH_AUTO_GROUPERS: 'Failed to refresh auto groupers',
  UPDATE_SYNC: 'Failed to update sync settings.',
  CHECK_MAINTENANCE: 'Failed to fetch maintenance mode status.',
  ENABLE_MAINTENANCE: 'Failed to enable maintenance mode.',
  UPDATE_MAINTENANCE: 'Failed to update maintenance mode.',
  REMOVE_MAINTENANCE: 'Failed to delete maintenance mode.',
  FETCH_DETAILS: 'Failed to fetch grouper details',
  FETCH_APPLICATION_DETAILS: 'Failed to fetch application details',
  UPDATE_APPLICATION: 'Failed to update application',
  DELETE_APPLICATION: 'Failed to delete application',
  FETCH_APPLICATION_SNAPSHOTS: 'Failed to fetch application snapshots',
  FETCH_SNAPSHOT_MANIFEST: 'Failed to fetch snapshot manifest',
  TRIGGER_APPLICATION_ROLLBACK: 'Failed to trigger application rollback',
  CHECK_INSIGHTS: 'Failed to check cluster insights',
  FETCH_APPS: 'Failed to fetch apps workloads',
  FETCH_BATCHES: 'Failed to fetch batches workloads',
  FETCH_APP_DETAILS: 'Failed to fetch app workload details',
  UPDATE_APP_SYNC: 'Failed to update app workload sync mode',
  TRIGGER_APPS_SYNC: 'Failed to trigger apps workloads sync',
  REFRESH_AUTO_GROUPERS_APPS: 'Failed to refresh auto apps workloads',
  FETCH_BRIDGES: 'Failed to fetch bridges',
  TRIGGER_BRIDGE_SYNC: 'Failed to trigger bridges sync',
  REFRESH_AUTO_BRIDGES: 'Failed to refresh auto bridges',
  FETCH_BRIDGE_DETAILS: 'Failed to fetch bridge details',
  UPDATE_BRIDGE_SYNC: 'Failed to update bridge sync settings.',
  FETCH_USERS: 'Failed to fetch users',
  FETCH_USER_DETAILS: 'Failed to fetch user details',
  CREATE_USER: 'Failed to create user',
  UPDATE_USER: 'Failed to update user',
  DELETE_USER: 'Failed to delete user',
  FETCH_PASSKEYS: 'Failed to fetch passkeys',
  FETCH_PASSKEY_DETAILS: 'Failed to fetch passkey details',
  CREATE_PASSKEY: 'Failed to create passkey',
  UPDATE_PASSKEY: 'Failed to update passkey',
  DELETE_PASSKEY: 'Failed to delete passkey',
  FETCH_GROUPS: 'Failed to fetch groups',
  FETCH_GROUP_DETAILS: 'Failed to fetch group details',
  CREATE_GROUP: 'Failed to create group',
  UPDATE_GROUP: 'Failed to update group',
  DELETE_GROUP: 'Failed to delete group',
  FETCH_ROLES: 'Failed to fetch roles',
  FETCH_ROLE_DETAILS: 'Failed to fetch role details',
  CREATE_ROLE: 'Failed to create role',
  UPDATE_ROLE: 'Failed to update role',
  DELETE_ROLE: 'Failed to delete role',
  FETCH_CATEGORIES: 'Failed to fetch categories',
} as const;

export const STORE_MESSAGES = {
  MAINTENANCE_UPDATED: 'Maintenance Mode updated:',
  FETCH_MAINTENANCE_FAILED: 'Failed to fetch maintenance data:',
  ERROR_FETCHING_GROUPERS: 'Error fetching groupers:',
  ERROR_FETCHING_GROUPER_DETAILS: 'Error fetching grouper details:',
  ERROR_FETCHING_APPLICATIONS: 'Error fetching applications:',
  ERROR_FETCHING_APPLICATION_DETAILS: 'Error fetching application details:',
  ERROR_UPDATING_APPLICATION: 'Error updating application:',
  ERROR_DELETING_APPLICATION: 'Error deleting application:',
  ERROR_FETCHING_APPLICATION_SNAPSHOTS: 'Error fetching application snapshots:',
  ERROR_FETCHING_SNAPSHOT_MANIFEST: 'Error fetching snapshot manifest:',
  ERROR_TRIGGERING_APPLICATION_ROLLBACK: 'Error triggering application rollback:',
  TRIGGERING_SYNC: 'Triggering SyncGrouper for:',
  ERROR_UPDATING_SYNC: 'Error updating sync settings:',
  ERROR_HANDLING_MAINTENANCE_UPDATE: 'Failed to handle maintenance mode update',
  ERROR_REMOVING_MAINTENANCE: 'Failed to remove maintenance mode',
  ERROR_BOUNDARY: 'Error caught in boundary:',
  ERROR_FETCHING_APPS: 'Error fetching apps workloads:',
  ERROR_FETCHING_BATCHES: 'Error fetching batches workloads:',
  ERROR_FETCHING_APP_DETAILS: 'Error fetching app workload details:',
  ERROR_UPDATING_APP_SYNC: 'Error updating app workload sync settings:',
  ERROR_FETCHING_BRIDGES: 'Error fetching bridges:',
  ERROR_FETCHING_BRIDGE_DETAILS: 'Error fetching bridge details:',
  ERROR_FETCHING_USERS: 'Error fetching users:',
  ERROR_FETCHING_USER_DETAILS: 'Error fetching user details:',
  ERROR_CREATING_USER: 'Error creating user:',
  ERROR_UPDATING_USER: 'Error updating user:',
  ERROR_DELETING_USER: 'Error deleting user:',
  ERROR_FETCHING_PASSKEYS: 'Error fetching passkeys:',
  ERROR_FETCHING_PASSKEY_DETAILS: 'Error fetching passkey details:',
  ERROR_CREATING_PASSKEY: 'Error creating passkey:',
  ERROR_UPDATING_PASSKEY: 'Error updating passkey:',
  ERROR_DELETING_PASSKEY: 'Error deleting passkey:',
  ERROR_FETCHING_GROUPS: 'Error fetching groups:',
  ERROR_FETCHING_GROUP_DETAILS: 'Error fetching group details:',
  ERROR_CREATING_GROUP: 'Error creating group:',
  ERROR_UPDATING_GROUP: 'Error updating group:',
  ERROR_DELETING_GROUP: 'Error deleting group:',
  ERROR_FETCHING_ROLES: 'Error fetching roles:',
  ERROR_FETCHING_ROLE_DETAILS: 'Error fetching role details:',
  ERROR_CREATING_ROLE: 'Error creating role:',
  ERROR_UPDATING_ROLE: 'Error updating role:',
  ERROR_DELETING_ROLE: 'Error deleting role:',
  ERROR_FETCHING_CATEGORIES: 'Error fetching categories:',
} as const;
