import { COMMON_VALUES } from '../shared/common';

export const STORAGE_KEYS = {
  HAS_CLUSTER_INSIGHTS: 'HAS_CLUSTER_INSIGHTS',
  WELCOME_PENDING: 'WELCOME_PENDING',
  RESOURCE_ACTIVE_TAB: 'RESOURCE_ACTIVE_TAB',
  SESSION_TOKEN: 'SESSION_TOKEN',
  CURRENT_USER: 'CURRENT_USER',
} as const;

export const STORE_ACTIONS = {
  INSIGHTS: {
    CHECK_CLUSTER: 'insights/checkCluster',
  },
  APPLICATIONS: {
    FETCH: 'applications/fetch',
    FETCH_SILENT: 'applications/fetchSilent',
    FETCH_DETAILS: 'applications/fetchDetails',
    FETCH_SNAPSHOTS: 'applications/fetchSnapshots',
    FETCH_SNAPSHOT_MANIFEST: 'applications/fetchSnapshotManifest',
    UPDATE: 'applications/update',
    DELETE: 'applications/delete',
    TRIGGER_ROLLBACK: 'applications/triggerRollback',
  },
  USERS: {
    FETCH: 'users/fetch',
    FETCH_SILENT: 'users/fetchSilent',
    FETCH_DETAILS: 'users/fetchDetails',
    CREATE: 'users/create',
    UPDATE: 'users/update',
    DELETE: 'users/delete',
  },
  GROUPS: {
    FETCH: 'groups/fetch',
    FETCH_SILENT: 'groups/fetchSilent',
    FETCH_DETAILS: 'groups/fetchDetails',
    CREATE: 'groups/create',
    UPDATE: 'groups/update',
    DELETE: 'groups/delete',
  },
  ROLES: {
    FETCH: 'roles/fetch',
    FETCH_SILENT: 'roles/fetchSilent',
    FETCH_DETAILS: 'roles/fetchDetails',
    CREATE: 'roles/create',
    UPDATE: 'roles/update',
    DELETE: 'roles/delete',
  },
  CATEGORIES: {
    FETCH_BY_SCOPE: 'categories/fetchByScope',
    FETCH_BY_SCOPE_SILENT: 'categories/fetchByScopeSilent',
  },
  PASSKEYS: {
    FETCH: 'passkeys/fetch',
    FETCH_SILENT: 'passkeys/fetchSilent',
    FETCH_DETAILS: 'passkeys/fetchDetails',
    CREATE: 'passkeys/create',
    UPDATE: 'passkeys/update',
    DELETE: 'passkeys/delete',
  },
  PERMISSIONS: {
    FETCH: 'permissions/fetch',
  },
  AUTH_CONFIG: {
    FETCH: 'authConfig/fetch',
    ENSURE: 'authConfig/ensure',
  },
  PROTECTION_PLANS: {
    FETCH: 'protectionPlans/fetch',
    FETCH_TEMPLATES: 'protectionPlans/fetchTemplates',
    FETCH_DETAILS: 'protectionPlans/fetchDetails',
    PREPARE: 'protectionPlans/prepare',
    CANCEL: 'protectionPlans/cancel',
    DELETE: 'protectionPlans/delete',
    DUPLICATE: 'protectionPlans/duplicate',
    PATCH: 'protectionPlans/patch',
    REACTIVATE: 'protectionPlans/reactivate',
  },
} as const;

export const SYNC_MODES = COMMON_VALUES.SYNC_MODES;

export const STORE_ERRORS = {
  FETCH_APPLICATIONS: 'Failed to fetch applications',
  FETCH_APPLICATION_DETAILS: 'Failed to fetch application details',
  UPDATE_APPLICATION: 'Failed to update application',
  DELETE_APPLICATION: 'Failed to delete application',
  FETCH_APPLICATION_SNAPSHOTS: 'Failed to fetch application snapshots',
  FETCH_SNAPSHOT_MANIFEST: 'Failed to fetch snapshot manifest',
  TRIGGER_APPLICATION_ROLLBACK: 'Failed to trigger application rollback',
  CHECK_INSIGHTS: 'Failed to check cluster insights',
  FETCH_USERS: 'Failed to fetch users',
  FETCH_USER_DETAILS: 'Failed to fetch user details',
  CREATE_USER: 'Failed to create user',
  UPDATE_USER: 'Failed to update user',
  DELETE_USER: 'Failed to delete user',
  FETCH_PASSKEYS: 'Failed to fetch passkeys',
  FETCH_PASSKEY_DETAILS: 'Failed to fetch passkey details',
  CREATE_PASSKEY: 'Failed to create passkey',
  UPDATE_PASSKEY: 'Failed to update passkey',
  DELETE_PASSKEY: 'Failed to delete passkey',
  FETCH_GROUPS: 'Failed to fetch groups',
  FETCH_GROUP_DETAILS: 'Failed to fetch group details',
  CREATE_GROUP: 'Failed to create group',
  UPDATE_GROUP: 'Failed to update group',
  DELETE_GROUP: 'Failed to delete group',
  FETCH_ROLES: 'Failed to fetch roles',
  FETCH_ROLE_DETAILS: 'Failed to fetch role details',
  CREATE_ROLE: 'Failed to create role',
  UPDATE_ROLE: 'Failed to update role',
  DELETE_ROLE: 'Failed to delete role',
  FETCH_CATEGORIES: 'Failed to fetch categories',
  FETCH_PERMISSIONS: 'Failed to fetch permissions',
  FETCH_AUTH_CONFIG: 'Failed to fetch auth config',
  FETCH_PROTECTION_PLANS: 'Failed to fetch protection plans',
  FETCH_PROTECTION_PLAN_TEMPLATES: 'Failed to fetch protection plan templates',
  PREPARE_PROTECTION_PLAN: 'Failed to prepare protection plan',
  CANCEL_PROTECTION_PLAN: 'Failed to cancel protection plan',
  DELETE_PROTECTION_PLAN: 'Failed to delete protection plan',
  DUPLICATE_PROTECTION_PLAN: 'Failed to duplicate protection plan',
  PATCH_PROTECTION_PLAN: 'Failed to update protection plan',
  REACTIVATE_PROTECTION_PLAN: 'Failed to reactivate protection plan',
  FETCH_PROTECTION_PLAN_DETAILS: 'Failed to fetch protection plan details',
} as const;

export const STORE_MESSAGES = {
  ERROR_FETCHING_APPLICATIONS: 'Error fetching applications:',
  ERROR_FETCHING_APPLICATION_DETAILS: 'Error fetching application details:',
  ERROR_UPDATING_APPLICATION: 'Error updating application:',
  ERROR_DELETING_APPLICATION: 'Error deleting application:',
  ERROR_FETCHING_APPLICATION_SNAPSHOTS: 'Error fetching application snapshots:',
  ERROR_FETCHING_SNAPSHOT_MANIFEST: 'Error fetching snapshot manifest:',
  ERROR_TRIGGERING_APPLICATION_ROLLBACK: 'Error triggering application rollback:',
  ERROR_BOUNDARY: 'Error caught in boundary:',
  ERROR_FETCHING_USERS: 'Error fetching users:',
  ERROR_FETCHING_USER_DETAILS: 'Error fetching user details:',
  ERROR_CREATING_USER: 'Error creating user:',
  ERROR_UPDATING_USER: 'Error updating user:',
  ERROR_DELETING_USER: 'Error deleting user:',
  ERROR_FETCHING_PASSKEYS: 'Error fetching passkeys:',
  ERROR_FETCHING_PASSKEY_DETAILS: 'Error fetching passkey details:',
  ERROR_CREATING_PASSKEY: 'Error creating passkey:',
  ERROR_UPDATING_PASSKEY: 'Error updating passkey:',
  ERROR_DELETING_PASSKEY: 'Error deleting passkey:',
  ERROR_FETCHING_GROUPS: 'Error fetching groups:',
  ERROR_FETCHING_GROUP_DETAILS: 'Error fetching group details:',
  ERROR_CREATING_GROUP: 'Error creating group:',
  ERROR_UPDATING_GROUP: 'Error updating group:',
  ERROR_DELETING_GROUP: 'Error deleting group:',
  ERROR_FETCHING_ROLES: 'Error fetching roles:',
  ERROR_FETCHING_ROLE_DETAILS: 'Error fetching role details:',
  ERROR_CREATING_ROLE: 'Error creating role:',
  ERROR_UPDATING_ROLE: 'Error updating role:',
  ERROR_DELETING_ROLE: 'Error deleting role:',
  ERROR_FETCHING_CATEGORIES: 'Error fetching categories:',
  ERROR_FETCHING_PERMISSIONS: 'Error fetching permissions:',
  ERROR_FETCHING_AUTH_CONFIG: 'Error fetching auth config:',
  ERROR_FETCHING_PROTECTION_PLANS: 'Error fetching protection plans:',
  ERROR_FETCHING_PROTECTION_PLAN_TEMPLATES: 'Error fetching protection plan templates:',
  ERROR_PREPARING_PROTECTION_PLAN: 'Error preparing protection plan:',
  ERROR_CANCELLING_PROTECTION_PLAN: 'Error cancelling protection plan:',
  ERROR_DELETING_PROTECTION_PLAN: 'Error deleting protection plan:',
  ERROR_DUPLICATING_PROTECTION_PLAN: 'Error duplicating protection plan:',
  ERROR_PATCHING_PROTECTION_PLAN: 'Error updating protection plan:',
  ERROR_REACTIVATING_PROTECTION_PLAN: 'Error reactivating protection plan:',
  ERROR_FETCHING_PROTECTION_PLAN_DETAILS: 'Error fetching protection plan details:',
} as const;
