import { DEFAULT_COLORS } from '../../../../constants';

export const IDE_MANIFEST_THEME = {
  bg: DEFAULT_COLORS.PAGE_BG,
  border: DEFAULT_COLORS.BORDER_ELEVATED,
  gutterText: DEFAULT_COLORS.ICON_MUTED,
  headerBg: DEFAULT_COLORS.SURFACE_ELEVATED,
  text: DEFAULT_COLORS.IDE_SYNTAX_TEXT,
  key: DEFAULT_COLORS.IDE_SYNTAX_KEY,
  string: DEFAULT_COLORS.IDE_SYNTAX_STRING,
  number: DEFAULT_COLORS.IDE_SYNTAX_NUMBER,
  keyword: DEFAULT_COLORS.IDE_SYNTAX_KEYWORD,
  punct: DEFAULT_COLORS.IDE_SYNTAX_TEXT,
  comment: DEFAULT_COLORS.IDE_SYNTAX_COMMENT,
  copyButton: DEFAULT_COLORS.IDE_SYNTAX_COPY_BUTTON,
} as const;
