export const ABOUT_SECTION_CONSTANTS = {
  LABELS: {
    VERSION_CARD_TITLE: 'Version',
    VERSION_CARD_DESCRIPTION: 'The dashboard version you are running.',
    DOCS_CARD_TITLE: 'Documentation',
    DOCS_CARD_DESCRIPTION: 'Guides and reference for Telark.',
    DOCS_LINK_TEXT: 'View documentation',
    LICENSES_CARD_TITLE: 'Third-Party Licenses',
    LICENSES_CARD_DESCRIPTION: 'Third-party software and assets in this app.',
    LICENSES_FULL_TEXT_LINK: 'Full license texts',
    LICENSES_SEARCH_PLACEHOLDER: 'Search packages...',
    LICENSES_LOAD_ERROR: 'Failed to load license information.',
    LICENSES_EMPTY: 'No packages match your search.',
  },
  LICENSES_LIST: {
    // Both files are generated by scripts/generate-licenses.mjs at build
    // time (npm run build/build:cluster) — never fetched or computed at runtime.
    JSON_URL: '/licenses.json',
    NOTICES_URL: '/THIRD-PARTY-NOTICES.txt',
    ROW_GAP: 8,
  },
  LINKS: {
    DOCS_URL: 'https://docs.telark.io',
  },
} as const;
