export const PROFILE_SECTION_CONSTANTS = {
  LAYOUT: {
    AVATAR_SIZE: 40,
    AVATAR_BORDER_WIDTH: 1.5,
    ROW_GAP: 12,
  },
  LABELS: {
    PROFILE_PHOTO_CARD_TITLE: 'Profile photo',
    PROFILE_PHOTO_CARD_DESCRIPTION: 'Your profile picture shown across the app.',
    PROFILE_DETAILS_CARD_TITLE: 'Account details',
    PROFILE_DETAILS_CARD_DESCRIPTION: 'Your personal and account information.',
    PROFILE_PHOTO: 'Profile photo',
    EDIT: 'Edit',
    EDIT_TITLE: 'Edit profile',
    FULL_NAME: 'Full name',
    USERNAME: 'Username',
    EMAIL: 'Email',
    MEMBER_SINCE: 'Member since',
    LAST_LOGIN: 'Last login',
    STATUS: 'Status',
    PLACEHOLDER: '—',
    EDIT_PROFILE_PANEL: {
      TITLE: 'Edit profile',
      SUBTITLE: 'Update your account details',
      USERNAME_LABEL: 'Username',
      FULLNAME_LABEL: 'Full name',
      FULLNAME_PLACEHOLDER: 'e.g. John Doe',
      EMAIL_LABEL: 'Email',
      EMAIL_PLACEHOLDER: 'e.g. john@example.com',
      SAVE: 'Save',
      CANCEL: 'Cancel',
      SUCCESS: 'Profile updated.',
      ERROR: 'Failed to update profile.',
    },
  },
} as const;
