export const PROFILE_SECTION_CONSTANTS = {
  // The profile fields a 409 names in its message ("user with this email already exists").
  CONFLICT_FIELDS: ['email', 'username'] as const,
  LAYOUT: {
    AVATAR_SIZE: 40,
    ROW_GAP: 12,
  },
  LABELS: {
    PROFILE_PHOTO_CARD_TITLE: 'Profile photo',
    PROFILE_PHOTO_CARD_DESCRIPTION: 'Your profile picture shown across the app.',
    PROFILE_DETAILS_CARD_TITLE: 'Account details',
    PROFILE_DETAILS_CARD_DESCRIPTION: 'Your personal and account information.',
    PROFILE_PHOTO: 'Profile photo',
    EDIT: 'Edit',
    EDIT_TITLE: 'Edit profile',
    FULL_NAME: 'Full name',
    USERNAME: 'Username',
    EMAIL: 'Email',
    MEMBER_SINCE: 'Member since',
    LAST_LOGIN: 'Last login',
    STATUS: 'Status',
    PLACEHOLDER: '—',
    AVATAR_UPDATE_SUCCESS: 'Profile photo updated.',
    AVATAR_UPDATE_ERROR: 'Failed to update profile photo.',
    EDIT_PROFILE_PANEL: {
      TITLE: 'Edit profile',
      USERNAME_LABEL: 'Username',
      USERNAME_PLACEHOLDER: 'e.g. john_doe',
      FULLNAME_LABEL: 'Full name',
      FULLNAME_PLACEHOLDER: 'e.g. John Doe',
      EMAIL_LABEL: 'Email',
      EMAIL_PLACEHOLDER: 'e.g. test@example.com',
      EMAIL_LOCKED:
        "The bootstrap admin's email is set when Telark is installed and can't be changed here.",
      EMAIL_RESERVED: 'This email is reserved for the bootstrap admin.',
      SAVE: 'Save',
      CANCEL: 'Cancel',
      SUCCESS: 'Profile updated.',
      ERROR: 'Failed to update profile.',
    },
  },
} as const;
