import { DEFAULT_COLORS } from '../shared/colors';

export const SCROLL_INDICATOR = {
  SIZE: 24,
  SCROLL_AMOUNT: 0.8,
  THRESHOLD: 5,
  BOTTOM_OFFSET: -10,
  ICON_SIZE_MULTIPLIER: 0.5,
  BACKGROUND_COLOR: DEFAULT_COLORS.SUCCESS,
  ICON_COLOR: '#fff',
  HOVER_OPACITY: 0.9,
  DEFAULT_OPACITY: 1,
  TRANSITION_DURATION: '0.2s',
  Z_INDEX: 2,
  CONTAINER: {
    position: 'absolute' as const,
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 2,
  },
  BUTTON: {
    borderRadius: '50%',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    boxShadow: 'none',
    padding: 0,
    margin: 0,
    outline: 'none',
    boxSizing: 'border-box' as const,
    position: 'relative' as const,
  },
  ICON_WRAPPER: {
    display: 'inline-block',
    lineHeight: 0,
    margin: 0,
    padding: 0,
    position: 'relative' as const,
  },
  ICON: {
    lineHeight: 1,
    margin: 0,
    padding: 0,
    display: 'block',
    position: 'absolute' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
} as const;
