import { DEFAULT_COLORS } from '../../../../constants';
import {
  DEFAULT_NAME_VALIDATION_CONFIG,
  type NameValidationConfig,
} from '../../../shared/constants/nameValidation';
import type {
  PlanApprovalMode,
  PlanPhase,
  PlanHealth,
  PlanMode,
  PlanReportFormat,
  ScopeType,
  ViolationResult,
} from '../models';

export const PROTECTION_PLANS_CONSTANTS = {
  LABELS: {
    HEADER_TITLE: 'Protection plans',
    HEADER_SUBTITLE:
      'Block chosen changes to an application or namespace for a set window. Audit first, then enforce.',
    NOT_FOUND: 'Protection plan not found',
    LOADING_PLANS: 'Loading Plans...',
    CREATE_BUTTON: 'Create Plan',
    CREATE_BUTTON_TEXT: 'Create Plan',
    TOOLBAR_SEARCH_PLACEHOLDER: 'Search plans by name, type, or scope...',
    TOOLBAR_SEARCH_BUTTON: 'Search',
    TOOLBAR_COUNT_SUFFIX: { one: 'plan', other: 'plans' },
    TOOLBAR_COMPACT_WIDTH: {
      DEFAULT: 760,
      BULK: 760,
    },
    // Natural width of the plans list row, from Geist advance widths calibrated
    // against the applications row: count + 7 phase pills with counts (~740px)
    // + filter + search + organize + create is ~1210px. Below this the pills
    // fold into one control; the labeled buttons (measured ~500px with the pills
    // folded) fall back to icons only below DEFAULT.
    LIST_TOOLBAR_COMPACT_WIDTH: {
      QUICK_FILTER: 1230,
      DEFAULT: 520,
      BULK: 520,
    },
    TOOLBAR_PHASE_FILTER: 'Filter by phase',
    BREADCRUMBS: {
      ROOT: 'Protection Plans',
      CREATE: 'Create Plan',
    },
    REPORTS: {
      GENERATE: 'Generate report',
      GENERATING: 'Generating…',
      REFRESH: 'Refresh',
      // Shared by the details page and the Reports tab.
      TRIGGER_LABELS: {
        manual: 'Manual',
        cancel: 'Plan canceled',
        end: 'Plan ended',
      },
      GENERATED_AT: 'Generated',
      GENERATED_BY: 'By',
      DECISIONS: 'Admission decisions',
      SYSTEM_ACTOR: 'System',
      TRUNCATED: 'capped',
      PRINT_HINT: 'Open the HTML report and use your browser’s Print to save it as PDF.',
      NOT_STARTED_HINT: 'Reports become available once the plan has started.',
      EMPTY_DRAFT: 'Reports become available once the plan starts.',
      EMPTY_ACTIVE:
        'No reports yet. Generate one now, or wait for the final report when the plan ends.',
      EMPTY_ENDED: 'No report was captured for this plan.',
      LOAD_ERROR: 'Could not load reports.',
      GENERATE_SUCCESS: 'Report generated.',
      GENERATE_ERROR: 'Could not generate the report.',
      GENERATE_BUSY: 'A report is already being generated. Try again in a moment.',
      DOWNLOAD_ERROR: 'Could not download the report.',
      DOWNLOAD_MISSING: 'This report file is no longer available.',
    },
    TABS: {
      PLANS: 'Plans',
      REPORTS: 'Reports',
    },
    REPORTS_TAB: {
      SEARCH_PLACEHOLDER: 'Search reports by plan name...',
      COUNT_SUFFIX: { one: 'report', other: 'reports' },
      REFRESH: 'Refresh',
      DOWNLOAD: 'Download',
      DELETED_PLAN: 'Deleted plan',
      EMPTY: 'No reports yet. A report is captured when a plan ends or is canceled.',
      NO_MATCH: 'No reports match the current search and filters.',
      TRUNCATED: (limit: number) => `Showing the newest ${limit} reports.`,
      COLUMNS: {
        GENERATED_AT: 'Generated',
        PLAN: 'Plan',
        ENVIRONMENT: 'Environment',
        TRIGGER: 'Trigger',
        GENERATED_BY: 'Generated by',
        VIOLATIONS: 'Violations',
      },
      FILTER: {
        BY_GENERATED_DATE: 'Generated date',
        BY_PLAN: 'Plan',
        BY_TRIGGER: 'Trigger',
      },
    },
    PERMISSION_DENIED: {
      CREATE: 'You do not have permission to create protection plans',
      EDIT: 'You do not have permission to edit protection plans',
      DUPLICATE: 'You do not have permission to duplicate protection plans',
      REACTIVATE: 'You do not have permission to reactivate protection plans',
      CANCEL: 'You do not have permission to cancel protection plans',
      DELETE: 'You do not have permission to delete protection plans',
      APPROVE: 'You do not have permission to approve protection plans',
      REJECT: 'You do not have permission to reject protection plans',
      GENERATE_REPORT: 'You do not have permission to generate reports',
      DOWNLOAD_REPORT: 'You do not have permission to download reports',
    },
    TAXONOMY: {
      BUTTON: 'Organize',
      ENVIRONMENTS: 'Environments',
      TAGS: 'Tags',
    },
    DETAIL_PAGE: {
      SUBTITLE: 'Check that the plan is in force, what it blocked or audited, and its reports.',
      LOADING_ERROR: 'Failed to load plan details.',
      NOT_FOUND: 'Protection plan not found.',
      SECTIONS: {
        OVERVIEW_TITLE: 'Overview',
        OVERVIEW_DESCRIPTION: 'Identity, mode, and lifecycle metadata.',
        OVERVIEW_COLUMN_PRIMARY: 'Details',
        OVERVIEW_COLUMN_PARTICIPANTS: 'Participants',
        SCOPE_TITLE: 'Scope',
        SCOPE_DESCRIPTION: 'What this plan protects.',
        POLICIES_TITLE: 'Policies',
        POLICIES_DESCRIPTION: 'Configured policy templates.',
        PARTICIPANTS_TITLE: 'Participants',
        PARTICIPANTS_DESCRIPTION: 'Users associated with this plan.',
        HEALTH_TITLE: 'Health',
        HEALTH_DESCRIPTION: 'Whether the policies this plan expects are live in the cluster.',
        VIOLATIONS_TITLE: 'Violations',
        VIOLATIONS_DESCRIPTION:
          'Recent admission decisions: what the plan blocked, audited or let through.',
        REPORTS_TITLE: 'Reports',
        REPORTS_DESCRIPTION:
          'What happened in the cluster while this plan was in effect. A final report is captured when the plan ends or is canceled.',
      },
      FIELDS: {
        ID: 'ID',
        NAME: 'Name',
        DESCRIPTION: 'Description',
        SEVERITY: 'Severity',
        PRIORITY: 'Priority',
        MODE: 'Mode',
        TIME_MODE: 'Time mode',
        TIME_RANGE: 'Time range',
        PERMANENT: 'Permanent',
        CREATED: 'Created By',
        UPDATED: 'Last updated',
        STARTED: 'Started By',
        TERMINATED: 'Terminated',
        REASON: 'Reason',
        SCOPE_TYPE: 'Scope type',
        APPLICATIONS: 'Applications',
        NAMESPACES: 'Namespaces',
        EXCLUDED_KINDS: 'Excluded kinds',
        EXCLUDED_RESOURCES: 'Excluded resources',
        EXECUTION: 'Execution',
        REQUESTED_BY: 'Requested By',
        APPROVED_BY: 'Approved By',
        REJECTED_BY: 'Rejected By',
        DECISION_COMMENT: 'Decision comment',
      },
      ACTIONS: {
        DUPLICATE: 'Duplicate',
        DUPLICATE_PANEL_TITLE: 'Duplicate Plan',
        CANCEL: 'Cancel',
        EDIT: 'Edit',
        MORE_LABEL: 'More',
        REFRESH_HEALTH: 'Refresh health',
        CANCEL_MODAL_TITLE: 'Cancel Protection Plan',
        CANCEL_MODAL_OK: 'Cancel plan',
        REACTIVATE: 'Reactivate',
        REACTIVATE_MODAL_TITLE: 'Reactivate Protection Plan',
        REACTIVATE_MODAL_BODY: 'Reactivate this plan? Its policies are redeployed to the cluster.',
        REACTIVATE_MODAL_OK: 'Reactivate',
        REACTIVATE_DISABLED_EXPIRED_TOOLTIP:
          "The plan's time range has expired. Edit its dates before reactivating.",
        APPROVE: 'Approve',
        REJECT: 'Reject',
        APPROVE_MODAL_TITLE: 'Approve Protection Plan',
        APPROVE_MODAL_BODY:
          'Approve this plan? Its policies are deployed to the cluster as soon as its schedule allows.',
        APPROVE_MODAL_OK: 'Approve',
        REJECT_MODAL_TITLE: 'Reject Protection Plan',
        REJECT_MODAL_BODY: 'Reject this plan? Nothing is deployed, and the requester is notified.',
        REJECT_MODAL_OK: 'Reject',
        DECISION_COMMENT_LABEL: 'Comment',
        DECISION_COMMENT_PLACEHOLDER: 'Add a comment for the requester',
        REJECT_COMMENT_REQUIRED: 'A comment is required to reject a plan.',
        SELF_DECISION_TOOLTIP: 'You requested this approval, so another approver must decide.',
        DECIDE_DISABLED_EXPIRED_TOOLTIP:
          "The plan's time range has expired, so it can no longer be approved.",
        DECISION_POLICIES_COUNT: (count: number) =>
          `${count} ${count === 1 ? 'policy' : 'policies'}`,
      },
      EMPTY_VALUE: '—',
    },
    EMPTY: {
      TITLE: 'No protection plans yet',
      DESCRIPTION:
        'Create a plan to block chosen changes to an application or namespace during a release or maintenance window. Start in audit mode, then enforce.',
    },
    MESSAGES: {
      ERROR_TITLE: 'Failed to load protection plans.',
    },
    ACTIONS: {
      CANCEL: 'Cancel plan',
      DELETE: 'Delete plan',
      DUPLICATE: 'Duplicate plan',
      DELETE_MODAL_TITLE: 'Delete Protection Plan',
      DELETE_MODAL_OK: 'Delete',
      DELETE_MODAL_NOTE:
        'Its reports, including the final report, are deleted with it. Download any report you need first.',
      DUPLICATE_SUCCESS: 'Plan duplicated.',
      DUPLICATE_ERROR: 'Failed to duplicate plan.',
      CANCEL_SUCCESS: (name: string) => `Plan "${name}" canceled.`,
      CANCEL_ERROR: 'Failed to cancel plan.',
      DELETE_SUCCESS: (name: string) => `Plan "${name}" deleted.`,
      DELETE_ERROR: 'Failed to delete plan.',
      REFRESH_HEALTH_ERROR: 'Failed to refresh health status.',
      CREATE_SUCCESS: (name: string) => `Plan "${name}" created.`,
      CREATE_ERROR: 'Failed to create plan.',
      UPDATE_SUCCESS: (name: string) => `Plan "${name}" updated.`,
      UPDATE_ERROR: 'Failed to update plan.',
      REACTIVATE_SUCCESS: (name: string) => `Plan "${name}" reactivated.`,
      REACTIVATE_ERROR: 'Failed to reactivate plan.',
      APPROVE_SUCCESS: (name: string) => `Plan "${name}" approved.`,
      APPROVE_ERROR: 'Failed to approve plan.',
      REJECT_SUCCESS: (name: string) => `Plan "${name}" rejected.`,
      REJECT_ERROR: 'Failed to reject plan.',
    },
    HEALTH_LABELS: {
      unknown: 'Unknown',
      healthy: 'Healthy',
      drifted: 'Drifted',
      degraded: 'Degraded',
    } as Record<PlanHealth, string>,
    VIOLATION_RESULT_LABELS: {
      pass: 'Pass',
      fail: 'Fail',
      warn: 'Warn',
      error: 'Error',
      skip: 'Skip',
    } as Record<ViolationResult, string>,
    VIOLATIONS: {
      TAB_LABEL: 'Violations',
      TABLE_RESOURCE: 'Resource',
      TABLE_RESOURCE_KIND: 'Kind',
      TABLE_RESOURCE_NAME: 'Resource',
      TABLE_NAMESPACE: 'Namespace',
      TABLE_RULE: 'Rule',
      TABLE_RESULT: 'Result',
      TABLE_TIMESTAMP: 'Timestamp',
      TABLE_MESSAGE: 'Message',
      EMPTY_TITLE: 'No violations in the retention window.',
      EMPTY_AUDIT: 'In audit mode, operations that would have been blocked appear here.',
      EMPTY_ENFORCE: 'Nothing matching this plan has been blocked recently.',
      RETENTION_NOTE: (window: string) =>
        `Admission decisions are kept for ${window}. Older ones are no longer available.`,
      LOAD_ERROR: 'Could not load violations.',
      LOAD_TIMEOUT: 'Could not load violations. The server took too long to respond.',
      REFRESH: 'Refresh',
      FILTER_PLACEHOLDER: 'Filter by result',
      FILTER_ALL: 'All',
    },
    HEALTH_DETAIL: {
      TITLE: 'Health',
      CHECKED_AT: 'Last checked',
      REFRESH_BUTTON: 'Refresh health',
      MISSING: 'Missing policies',
      UNEXPECTED: 'Unexpected policies',
      POLICY_NAME: 'Policy',
      NAMESPACE: 'Namespace',
      PRESENT: 'Present',
      READY: 'Ready',
      FAILURE_ACTION: 'Failure action',
      LOAD_ERROR: 'Failed to load health status.',
    },
    PHASE_LABELS: {
      active: 'Active',
      scheduled: 'Scheduled',
      failed: 'Failed',
      terminated: 'Terminated',
      canceled: 'Canceled',
      draft: 'Draft',
      pending_approval: 'Pending approval',
    } as Record<PlanPhase, string>,
    PHASE_INFO: {
      STARTS_PREFIX: 'Starts',
      STARTS_IN_PREFIX: 'Starts in',
      ENDS_PREFIX: 'Ends',
      ENDS_IN_PREFIX: 'Ends in',
      TERMINATED_PREFIX: 'Terminated',
      AWAITING_APPROVAL_PREFIX: 'Awaiting approval · requested',
      REJECTED_LABEL: 'Rejected',
    },
    MODE_LABELS: {
      audit: 'Audit',
      enforce: 'Enforce',
    } as Record<PlanMode, string>,
    EXECUTION_LABELS: {
      automatic: 'Automatic',
      required: 'Requires approval',
    } as Record<PlanApprovalMode, string>,
    CARD: {
      WINDOW_LABEL: 'Protection window',
      PERMANENT_LABEL: 'Protection',
      WINDOW_TIME_FORMAT: 'MMM d, HH:mm',
      RANGE_SEPARATOR: ' → ',
      PERMANENT_RANGE: 'Always on',
      NO_END_DATE: 'No end date',
      NO_SCHEDULE: 'No schedule set',
      META_SEPARATOR: ' · ',
      TARGETS_SEPARATOR: ', ',
      APPLICATIONS_COUNT: (count: number) =>
        `${count} ${count === 1 ? 'application' : 'applications'}`,
      CREATED_PREFIX: 'created',
      UPDATED_PREFIX: 'updated',
      REFUSES_PREFIX: 'Refuses',
      REFUSES_NONE: 'No policies configured',
      MORE_POLICIES: (count: number) => `+${count}`,
      STATE: {
        ENFORCING: 'Enforcing',
        AUDITING: 'Auditing in the background',
        SCHEDULED: 'Waiting to start',
        CANCELED: 'Canceled',
        TERMINATED: 'Window ended',
        FAILED: 'Could not deploy',
        DRAFT: 'Draft',
      },
      LEFT_SUFFIX: 'left',
      STATS: {
        SCOPE: 'Scope',
        MODE: 'Mode',
        TEMPLATES: 'Templates',
        HEALTH: 'Health',
      },
      TEMPLATES_COUNT: (count: number) => `${count} active`,
      NAMESPACES_COUNT: (count: number) => `${count} ${count === 1 ? 'namespace' : 'namespaces'}`,
      BLOCKED_LABEL: 'Refuses in this window',
      BLOCKED_LABEL_PERMANENT: 'Always refuses',
      CREATED_BY_PREFIX: 'by',
      AWAITING_APPROVAL_BY_PREFIX: 'awaiting approval · requested by',
      PROTECTING_NAMESPACE: (target: string) => `Protecting namespace ${target}`,
      PROTECTING_NAMESPACES: (count: number) => `Protecting ${count} namespaces`,
      PROTECTING_APPLICATIONS: (count: number) =>
        `Protecting ${count} ${count === 1 ? 'application' : 'applications'}`,
    },
    SEVERITY_LABEL: 'Severity',
    MODE_ENFORCEMENT_LABEL: 'Policy Enforcement Mode',
    QUICK_FILTERS: {
      ALL: 'All',
    },
    FILTER: {
      BY_CREATION_DATE: 'Created date',
      BY_SCOPE_TYPE: 'Scope type',
      BY_CREATED_BY: 'Created by',
      BY_TEMPLATES: 'Templates',
      BY_TARGETS: 'Targets',
      BY_ENVIRONMENT: 'Environment',
      BY_TAGS: 'Tags',
      FROM: 'From',
      TO: 'To',
    },
  },
  FILTER_KEYS: {
    DATE_RANGE: 'dateRange',
    SCOPE_TYPE: 'scopeType',
    CREATED_BY: 'createdBy',
    TEMPLATES: 'templates',
    TARGETS: 'targets',
    ENVIRONMENT: 'environment',
    TAGS: 'tags',
    PLAN: 'plan',
    TRIGGER: 'trigger',
  } as const,
  PANELS: {
    CREATE: {
      TITLE: 'Create Protection Plan',
      SUBMIT_BUTTON: 'Create Plan',
      LOADING_LABEL: 'Creating...',
    },
    EDIT: {
      TITLE: 'Edit Protection Plan',
      SUBMIT_BUTTON: 'Save changes',
      LOADING_LABEL: 'Saving...',
      ACTIVE_SCOPE_WARNING: 'Saving a scope change redeploys this plan’s policies.',
      NO_CHANGES_HINT: 'No changes to save.',
      APPROVED_LOCKED_ALERT:
        'This plan was approved as configured, so scope, policies, schedule and mode are locked. To change them, duplicate the plan, or cancel and reactivate it to request a new approval.',
    },
  },
  CREATE_PAGE: {
    GAP_BETWEEN_CARDS: 18,
    SECTIONS: {
      BASIC_INFO_TITLE: 'Details',
      BASIC_INFO_DESCRIPTION: 'Name, description, severity and priority.',
      CLASSIFICATION_TITLE: 'Classification',
      CLASSIFICATION_DESCRIPTION: 'Environment and tags used to organize and filter plans.',
      APPROVAL_TITLE: 'Execution & approval',
      APPROVAL_DESCRIPTION: 'Whether the plan deploys on its own or waits for an approver.',
      PARTICIPANTS_TITLE: 'Participants',
      PARTICIPANTS_DESCRIPTION: 'Select users to associate with this plan.',
      SCOPE_TITLE: 'Scope',
      SCOPE_DESCRIPTION: 'Choose what to protect: applications or namespaces.',
      SCHEDULE_TITLE: 'Schedule',
      SCHEDULE_DESCRIPTION: 'Set the protection window, or keep the plan on until you end it.',
      POLICIES_TITLE: 'Policies',
      POLICIES_DESCRIPTION:
        'Pick the changes to block from policy templates, then audit or enforce.',
    },
    FORM: {
      NAME_LABEL: 'Plan name',
      NAME_PLACEHOLDER: 'e.g. Production release freeze',
      DESCRIPTION_LABEL: 'Description',
      DESCRIPTION_PLACEHOLDER: 'Optional short description',
      SEVERITY_LABEL: 'Severity',
      PRIORITY_LABEL: 'Priority',
      MODE_LABEL: 'Mode',
      SCOPE_TYPE_LABEL: 'Scope type',
      APPLICATIONS_LABEL: 'Applications',
      APPLICATIONS_PLACEHOLDER: 'Select applications',
      NAMESPACES_LABEL: 'Namespaces',
      NAMESPACES_PLACEHOLDER: 'Enter namespace names',
      EXCLUDED_KINDS_LABEL: 'Excluded kinds',
      EXCLUDED_KINDS_PLACEHOLDER: 'Kinds this plan will not enforce on',
      EXCLUDED_RESOURCES_LABEL: 'Excluded resources',
      EXCLUDED_RESOURCES_PLACEHOLDER: 'Resources of the selected applications to leave unprotected',
      EXCLUSIONS_NAMESPACES_HINT: 'Only kinds can be excluded for a namespace scope.',
      EXCLUSIONS_SELECT_APPS_HINT: 'Select applications to load their resources.',
      TIME_MODE_LABEL: 'Mode',
      START_AT_LABEL: 'Start',
      END_AT_LABEL: 'End',
      PARTICIPANTS_LABEL: 'Participants',
      PARTICIPANTS_PLACEHOLDER: 'Select participants',
      ADD_POLICY_BUTTON: 'Add policy',
      POLICIES_REQUIRED_ERROR: 'Add at least one policy to continue.',
      PARAM_REQUIRED_ERROR: 'Enter at least one value.',
      PARAM_PATTERN_ERROR: (value: string) => `"${value}" is not a valid value.`,
      NAME_REQUIRED_ERROR: 'Plan name is required',
      PARAM_PLACEHOLDER: (label: string) => `Enter ${label.toLowerCase()}`,
      START_REQUIRED_ERROR: 'Start time is required',
      END_REQUIRED_ERROR: 'End time is required',
      SEVERITY_REQUIRED_ERROR: 'Severity is required',
      APPLICATIONS_REQUIRED_ERROR: 'Select at least one application',
      NAMESPACES_REQUIRED_ERROR: 'Select at least one namespace',
      ENVIRONMENT_LABEL: 'Environment',
      ENVIRONMENT_PLACEHOLDER: 'Select an environment (optional)',
      TAGS_LABEL: 'Tags',
      TAGS_PLACEHOLDER: 'Select tags (optional)',
      APPROVAL_MODE_LABEL: 'Execution',
      APPROVAL_HELP_REQUIRED: 'Nothing is deployed until an approver confirms the plan.',
      APPROVAL_HELP_AUTOMATIC: 'Policies are deployed as soon as the plan starts.',
      APPROVAL_PRODUCTION_HINT: 'Production plans usually require approval.',
      APPROVAL_MODE_IMMUTABLE_TOOLTIP:
        'Execution cannot be changed after creation. Duplicate the plan to change it.',
    },
    SEVERITY_OPTIONS: [
      { value: 'low', label: 'Low' },
      { value: 'medium', label: 'Medium' },
      { value: 'high', label: 'High' },
      { value: 'critical', label: 'Critical' },
    ] as Array<{ value: string; label: string }>,
    APPROVAL_MODE_OPTIONS: [
      { value: 'automatic', label: 'Automatic: deploys as soon as the plan starts' },
      {
        value: 'required',
        label: 'Requires approval: an approver must confirm before anything is deployed',
      },
    ] as Array<{ value: string; label: string }>,
    MODE_OPTIONS: [
      { value: 'audit', label: 'Audit: log violations, do not block' },
      { value: 'enforce', label: 'Enforce: block policy violations' },
    ] as Array<{ value: string; label: string }>,
    TIME_MODE_OPTIONS: [
      { value: 'permanent', label: 'Permanent' },
      { value: 'time_range', label: 'Time range' },
    ] as Array<{ value: string; label: string }>,
    SCOPE_TYPE_OPTIONS: [
      { value: 'applications', label: 'Applications' },
      { value: 'namespaces', label: 'Namespaces' },
    ] as Array<{ value: string; label: string }>,
  },
} as const;

// The backend's priority range starts at -100.
export const PLAN_PRIORITY_MIN = -100;

// Same rules as the backend's plan name checks; the create form and Duplicate share them.
export const PLAN_NAME_VALIDATION: NameValidationConfig = {
  ...DEFAULT_NAME_VALIDATION_CONFIG,
  maxLength: 64,
  allowedPattern: /^[a-zA-Z0-9_\- ]+$/,
  duplicateErrorMessage: 'A plan with this name already exists',
  invalidCharsErrorMessage:
    'Name can only contain letters, numbers, spaces, hyphens (-), and underscores (_)',
};

export const PLAN_TAXONOMY_LIMITS = { MAX_TAGS: 20 } as const;

// Tags per row on a plan card; the rest go behind the "+N" pill.
export const PLAN_CARD_MAX_TAGS = 2;

// mirrors internal/data constants.CategoryIDEnvProduction
export const PLAN_APPROVAL = {
  PRODUCTION_ENVIRONMENT_ID: 'cat-00002-0001-0001',
  COMMENT_MAX: 500,
} as const;

export const REPORT_FORMATS: ReadonlyArray<{ key: PlanReportFormat; label: string }> = [
  { key: 'html', label: 'HTML' },
  { key: 'md', label: 'Markdown' },
  { key: 'json', label: 'JSON' },
  { key: 'csv', label: 'CSV' },
];

export const REPORT_GENERATE_TIMEOUT_MS = 35_000;
export const REPORT_DOWNLOAD_TIMEOUT_MS = 60_000;
export const OBJECT_URL_REVOKE_DELAY_MS = 1_000;
export const REPORT_BUSY_STATUS = 429;
export const REPORT_SYSTEM_USER_ID = 'system';

export const PLANS_PAGE_TAB_PARAM = 'tab';

export const REPORTS_LIST = {
  // The exporter's maximum; the tab fetches once and filters client-side.
  LIMIT: 1000,
  PAGE_SIZE: 20,
  PAGE_SIZE_OPTIONS: [20, 50, 100],
  // Same control set as the users row (count, filter, search, one icon
  // button), measured there at ~475px.
  TOOLBAR_COMPACT_WIDTH: { DEFAULT: 530, BULK: 530 },
  COLUMN_WIDTHS: {
    GENERATED_AT: 150,
    PLAN: 220,
    ENVIRONMENT: 150,
    TRIGGER: 150,
    GENERATED_BY: 160,
    VIOLATIONS: 110,
    ACTIONS: 140,
  },
} as const;

export { CARD_LAYOUT } from '../../../../constants';

export const PHASE_ACCENT: Record<PlanPhase, string> = {
  active: DEFAULT_COLORS.SUCCESS,
  scheduled: DEFAULT_COLORS.WARNING,
  failed: DEFAULT_COLORS.DANGER,
  terminated: DEFAULT_COLORS.NEUTRAL,
  canceled: DEFAULT_COLORS.NEUTRAL,
  draft: DEFAULT_COLORS.NEUTRAL,
  pending_approval: DEFAULT_COLORS.WARNING,
};

export const HEALTH_ACCENT: Record<PlanHealth, string> = {
  unknown: DEFAULT_COLORS.NEUTRAL,
  healthy: DEFAULT_COLORS.SUCCESS,
  drifted: DEFAULT_COLORS.WARNING,
  degraded: DEFAULT_COLORS.DANGER,
};

/**
 * Chip text per template: the card names the operation a plan refuses, so
 * "Storage" alone never leaves the reader guessing which change is blocked.
 */
export const POLICY_CHIP_LABEL: Record<string, string> = {
  'block-create': 'Creating any resource',
  'block-update': 'Updating any resource',
  'block-delete': 'Deleting any resource',
  'block-image-types': 'Images matching blocked patterns',
  'block-image-tags': 'Images with blocked tags',
  'block-replica-scaling': 'Changing replica counts',
  'block-storage-changes': 'Creating, deleting or editing storage',
  'block-config-secret-resource-changes': 'Updating or deleting ConfigMaps & Secrets',
  'block-workload-config-mount-changes': 'Changing config mounts & env sources',
};

export const SCOPE_TYPE_LABEL: Record<ScopeType, string> = {
  applications: PROTECTION_PLANS_CONSTANTS.LABELS.DETAIL_PAGE.FIELDS.APPLICATIONS,
  namespaces: PROTECTION_PLANS_CONSTANTS.LABELS.DETAIL_PAGE.FIELDS.NAMESPACES,
};

export const PHASE_DOT_COLOR: Record<PlanPhase, string> = PHASE_ACCENT;

export const HEALTH_DOT_COLOR: Record<PlanHealth, string> = HEALTH_ACCENT;

export const VIOLATION_RESULT_DOT: Record<ViolationResult, string> = {
  pass: DEFAULT_COLORS.SUCCESS,
  fail: DEFAULT_COLORS.DANGER,
  warn: DEFAULT_COLORS.WARNING,
  error: DEFAULT_COLORS.DANGER,
  skip: DEFAULT_COLORS.NEUTRAL,
};
