import { DEFAULT_COLORS } from '../../../../constants';
import type { PlanPhase, PlanHealth, ViolationResult } from '../models';

export const PROTECTION_PLANS_CONSTANTS = {
  LABELS: {
    HEADER_TITLE: 'Protection Plans',
    HEADER_SUBTITLE:
      'Define temporary protection windows to safeguard critical Kubernetes workloads.',
    CREATE_SUBTITLE: 'Create a new Protection Plan',
    NOT_FOUND: 'Protection Plan not found',
    LOADING_PLANS: 'Loading Plans...',
    CREATE_BUTTON: 'Create Plan',
    CREATE_BUTTON_TEXT: 'Create Plan',
    BREADCRUMBS: {
      ROOT: 'Protection Plans',
      CREATE: 'Create Plan',
    },
    DETAIL_PAGE: {
      SUBTITLE: 'Inspect plan configuration, health, and recent violations.',
      LOADING_ERROR: 'Failed to load plan details.',
      NOT_FOUND: 'Protection plan not found.',
      SECTIONS: {
        OVERVIEW_TITLE: 'Overview',
        OVERVIEW_DESCRIPTION: 'Identity, mode, and lifecycle metadata.',
        OVERVIEW_COLUMN_PRIMARY: 'Details',
        OVERVIEW_COLUMN_PARTICIPANTS: 'Participants',
        SCOPE_TITLE: 'Scope',
        SCOPE_DESCRIPTION: 'What this plan protects.',
        POLICIES_TITLE: 'Policies',
        POLICIES_DESCRIPTION: 'Configured policy templates.',
        PARTICIPANTS_TITLE: 'Participants',
        PARTICIPANTS_DESCRIPTION: 'Users associated with this plan.',
        HEALTH_TITLE: 'Health',
        HEALTH_DESCRIPTION: 'Drift detection across deployed policies.',
        VIOLATIONS_TITLE: 'Violations',
        VIOLATIONS_DESCRIPTION: 'Recent policy admission decisions.',
      },
      FIELDS: {
        ID: 'ID',
        NAME: 'Name',
        DESCRIPTION: 'Description',
        SEVERITY: 'Severity',
        PRIORITY: 'Priority',
        MODE: 'Mode',
        TIME_MODE: 'Time mode',
        TIME_RANGE: 'Time range',
        PERMANENT: 'Permanent',
        CREATED: 'Created By',
        UPDATED: 'Last updated',
        STARTED: 'Started By',
        TERMINATED: 'Terminated',
        REASON: 'Reason',
        SCOPE_TYPE: 'Scope type',
        APPLICATIONS: 'Applications',
        NAMESPACES: 'Namespaces',
      },
      ACTIONS: {
        DUPLICATE: 'Duplicate',
        DUPLICATE_PANEL_TITLE: 'Duplicate Plan',
        CANCEL: 'Cancel',
        EDIT: 'Edit',
        EDIT_DISABLED_TOOLTIP: 'Cannot edit a terminated or canceled plan.',
        REFRESH_HEALTH: 'Refresh health',
        CANCEL_MODAL_TITLE: 'Cancel Protection Plan',
        CANCEL_MODAL_OK: 'Cancel plan',
        REACTIVATE: 'Reactivate',
        REACTIVATE_MODAL_TITLE: 'Reactivate Protection Plan',
        REACTIVATE_MODAL_BODY:
          "Reactivate this protection plan? Its policies will be re-deployed to the cluster.",
        REACTIVATE_MODAL_OK: 'Reactivate',
        REACTIVATE_DISABLED_EXPIRED_TOOLTIP:
          "The plan's time range has expired. Edit the plan to set new dates before reactivating.",
      },
      EMPTY_VALUE: '—',
    },
    EMPTY: {
      TITLE: 'No protection plans yet',
      DESCRIPTION:
        'Create a plan to protect namespaces or applications during maintenance windows and critical operations.',
      BUTTON: 'Create Protection Plan',
    },
    MESSAGES: {
      ERROR_TITLE: 'Failed to load Protection Plans.',
    },
    ACTIONS: {
      CANCEL: 'Cancel plan',
      DELETE: 'Delete plan',
      DUPLICATE: 'Duplicate plan',
      DELETE_MODAL_TITLE: 'Delete Protection Plan',
      DELETE_MODAL_OK: 'Delete',
      DUPLICATE_SUCCESS: 'Plan duplicated successfully.',
      DUPLICATE_ERROR: 'Failed to duplicate plan.',
      CREATE_SUCCESS: (name: string) => `Plan "${name}" created.`,
      CREATE_ERROR: 'Failed to create plan.',
      UPDATE_SUCCESS: (name: string) => `Plan "${name}" updated.`,
      UPDATE_ERROR: 'Failed to update plan.',
      REACTIVATE_SUCCESS: (name: string) => `Plan "${name}" reactivated.`,
      REACTIVATE_ERROR: 'Failed to reactivate plan.',
    },
    HEALTH_LABELS: {
      unknown: 'Unknown',
      healthy: 'Healthy',
      drifted: 'Drifted',
      degraded: 'Degraded',
    } as Record<PlanHealth, string>,
    VIOLATION_RESULT_LABELS: {
      pass: 'Pass',
      fail: 'Fail',
      warn: 'Warn',
      error: 'Error',
      skip: 'Skip',
    } as Record<ViolationResult, string>,
    VIOLATIONS: {
      TAB_LABEL: 'Violations',
      TABLE_RESOURCE: 'Resource',
      TABLE_RESOURCE_KIND: 'Kind',
      TABLE_RESOURCE_NAME: 'Resource',
      TABLE_NAMESPACE: 'Namespace',
      TABLE_RULE: 'Rule',
      TABLE_RESULT: 'Result',
      TABLE_TIMESTAMP: 'Timestamp',
      TABLE_MESSAGE: 'Message',
      EMPTY_TITLE: 'No violations recorded yet.',
      EMPTY_AUDIT: 'In audit mode, the engine logs what would have been blocked here.',
      EMPTY_ENFORCE: 'All operations matching your policies have been enforced.',
      LOAD_ERROR: 'Could not load violations. The server took too long to respond.',
      REFRESH: 'Refresh',
      FILTER_PLACEHOLDER: 'Filter by result',
      FILTER_ALL: 'All',
    },
    HEALTH_DETAIL: {
      TITLE: 'Health',
      CHECKED_AT: 'Last checked',
      REFRESH_BUTTON: 'Refresh health',
      MISSING: 'Missing policies',
      UNEXPECTED: 'Unexpected policies',
      POLICY_NAME: 'Policy',
      NAMESPACE: 'Namespace',
      PRESENT: 'Present',
      READY: 'Ready',
      FAILURE_ACTION: 'Failure action',
      LOAD_ERROR: 'Failed to load health status.',
    },
    PHASE_LABELS: {
      active: 'Active',
      scheduled: 'Scheduled',
      failed: 'Failed',
      terminated: 'Terminated',
      canceled: 'Canceled',
      draft: 'Draft',
    } as Record<PlanPhase, string>,
    PHASE_INFO: {
      STARTS_PREFIX: 'Starts',
      ENDS_PREFIX: 'Ends',
      ENDS_IN_PREFIX: 'Ends in',
      TERMINATED_PREFIX: 'Terminated',
    },
    SEVERITY_LABEL: 'Severity',
    MODE_ENFORCEMENT_LABEL: 'Policy Enforcement Mode',
  },
  PANELS: {
    CREATE: {
      TITLE: 'Create Protection Plan',
      SUBTITLE: 'Define a new protection window for your workloads.',
      SUBMIT_BUTTON: 'Create Plan',
      LOADING_LABEL: 'Creating...',
    },
    EDIT: {
      TITLE: 'Edit Protection Plan',
      SUBTITLE: (name: string) => `Update configuration of "${name}".`,
      SUBMIT_BUTTON: 'Save changes',
      LOADING_LABEL: 'Saving...',
      ACTIVE_SCOPE_WARNING:
        'Saving changes to scope will re-render and re-deploy this plan’s policies.',
      NO_CHANGES_HINT: 'No changes to save.',
    },
  },
  CREATE_PAGE: {
    GAP_BETWEEN_CARDS: 20,
    SECTIONS: {
      BASIC_INFO_TITLE: 'Basic information',
      BASIC_INFO_DESCRIPTION: 'Name, description, severity, priority and mode.',
      SCOPE_TITLE: 'Scope',
      SCOPE_DESCRIPTION: 'Choose what to protect: by applications or by namespaces.',
      SCHEDULE_TITLE: 'Schedule',
      SCHEDULE_DESCRIPTION: 'Set the protection window — permanent or time-bounded.',
      POLICIES_TITLE: 'Policies',
      POLICIES_DESCRIPTION: 'Choose which policy templates to enforce.',
    },
    FORM: {
      NAME_LABEL: 'Plan name',
      NAME_PLACEHOLDER: 'e.g. Production release freeze',
      DESCRIPTION_LABEL: 'Description',
      DESCRIPTION_PLACEHOLDER: 'Optional short description',
      SEVERITY_LABEL: 'Severity',
      PRIORITY_LABEL: 'Priority',
      MODE_LABEL: 'Mode',
      SCOPE_TYPE_LABEL: 'Scope type',
      APPLICATIONS_LABEL: 'Applications',
      APPLICATIONS_PLACEHOLDER: 'Select applications',
      NAMESPACES_LABEL: 'Namespaces',
      NAMESPACES_PLACEHOLDER: 'Enter namespace names',
      TIME_MODE_LABEL: 'Mode',
      START_AT_LABEL: 'Start',
      END_AT_LABEL: 'End',
      PARTICIPANTS_LABEL: 'Participants',
      PARTICIPANTS_PLACEHOLDER: 'Select participants',
      ADD_POLICY_BUTTON: 'Add policy',
    },
    SEVERITY_OPTIONS: [
      { value: 'low', label: 'Low' },
      { value: 'medium', label: 'Medium' },
      { value: 'high', label: 'High' },
      { value: 'critical', label: 'Critical' },
    ] as Array<{ value: string; label: string }>,
    MODE_OPTIONS: [
      { value: 'audit', label: 'Audit — log violations, do not block' },
      { value: 'enforce', label: 'Enforce — block policy violations' },
    ] as Array<{ value: string; label: string }>,
    TIME_MODE_OPTIONS: [
      { value: 'permanent', label: 'Permanent' },
      { value: 'time_range', label: 'Time range' },
    ] as Array<{ value: string; label: string }>,
    SCOPE_TYPE_OPTIONS: [
      { value: 'applications', label: 'Applications' },
      { value: 'namespaces', label: 'Namespaces' },
    ] as Array<{ value: string; label: string }>,
  },
} as const;

export const PHASE_BADGE_CONFIG: Record<PlanPhase, { background: string; color: string }> = {
  active: { background: '#dcfce7', color: '#166534' },
  scheduled: { background: '#dbeafe', color: '#1d4ed8' },
  failed: { background: '#fee2e2', color: '#991b1b' },
  terminated: { background: '#e5e7eb', color: '#4b5563' },
  canceled: { background: '#e5e7eb', color: '#4b5563' },
  draft: { background: '#f3f4f6', color: '#6b7280' },
};

export const PHASE_DOT_COLOR: Record<PlanPhase, string> = {
  active: '#22c55e',
  scheduled: '#3b82f6',
  failed: '#ef4444',
  terminated: '#9ca3af',
  canceled: '#9ca3af',
  draft: '#d1d5db',
};

export const HEALTH_DOT_COLOR: Record<PlanHealth, string> = {
  unknown: '#9ca3af',
  healthy: '#22c55e',
  drifted: '#f59e0b',
  degraded: '#ef4444',
};

export const HEALTH_BADGE_CONFIG: Record<PlanHealth, { background: string; color: string }> = {
  unknown: { background: '#f3f4f6', color: '#6b7280' },
  healthy: { background: '#dcfce7', color: '#166534' },
  drifted: { background: '#fef3c7', color: '#92400e' },
  degraded: { background: '#fee2e2', color: '#991b1b' },
};

export const VIOLATION_RESULT_BADGE: Record<
  ViolationResult,
  { background: string; color: string }
> = {
  pass: { background: '#dcfce7', color: '#166534' },
  fail: { background: '#fee2e2', color: '#991b1b' },
  warn: { background: '#fef3c7', color: '#92400e' },
  error: { background: '#fecaca', color: '#7f1d1d' },
  skip: { background: '#e5e7eb', color: '#4b5563' },
};

export const VIOLATION_RESULT_DOT: Record<ViolationResult, string> = {
  pass: DEFAULT_COLORS.SUCCESS,
  fail: DEFAULT_COLORS.DANGER,
  warn: DEFAULT_COLORS.WARNING,
  error: DEFAULT_COLORS.ERROR,
  skip: DEFAULT_COLORS.DEFAULT,
};
