export const LOGIN_CONSTANTS = {
  ERROR_PATTERNS: {
    USER_NOT_FOUND: ['user not found', 'failed to get user', 'status: 404'],
    NO_PASSKEYS: ['no passkeys found', 'no passkey found', 'no passkeys', 'no passkey'],
    ACCOUNT_SUSPENDED: ['account is suspended'],
    BOOTSTRAP_PASSKEY_ONLY: ['bootstrap administrator signs in with a passkey'],
  },
  MESSAGES: {
    USER_NOT_FOUND: 'No account for this email yet. Register first, or check the address.',
    USER_NOT_FOUND_NO_SELF_REGISTRATION:
      'No account for this email. Check the address, or contact your administrator.',
    NO_PASSKEYS: 'This account has no passkey yet. Contact your administrator.',
    LOST_PASSKEY: 'Contact your administrator to restore access to this account.',
    ACCOUNT_SUSPENDED: 'Your Telark account is suspended. Contact your administrator.',
    BOOTSTRAP_PASSKEY_ONLY:
      "Google sign-in isn't available for the bootstrap administrator. Sign in with its passkey.",
    NETWORK_ERROR: 'Network error. Please check your connection and try again.',
    TIMEOUT_ERROR: 'Request timed out. Please try again.',
    SERVER_ERROR: 'Server error. Please try again later.',
    CLIENT_ERROR: 'Invalid request. Please check your input and try again.',
    INVALID_RESPONSE: 'Invalid response from server. Please try again.',
  },
  TIMING: {
    MESSAGE_DURATION: 4,
    CALLBACK_DELAY: 2000,
  },
  WEBAUTHN: {
    USER_VERIFICATION: 'preferred',
    USER_VERIFICATION_DISCOURAGED: 'discouraged',
    CREDENTIAL_TYPE: 'public-key' as const,
    ATTESTATION: 'none',
    SHOW_ALL_PASSKEYS: true,
    TIMEOUT: {
      VALIDATION_CHECK: 1000,
    },
    REGEX: {
      BASE64URL_TO_BASE64: {
        REPLACE_DASH: /-/g,
        REPLACE_UNDERSCORE: /_/g,
        REPLACE_WITH_PLUS: '+',
        REPLACE_WITH_SLASH: '/',
      },
      BASE64_TO_BASE64URL: {
        REPLACE_PLUS: /\+/g,
        REPLACE_SLASH: /\//g,
        REPLACE_TRAILING_EQUALS: /={1,2}$/,
        REPLACE_WITH_DASH: '-',
        REPLACE_WITH_UNDERSCORE: '_',
      },
    },
    ERROR_NAMES: {
      NOT_ALLOWED: 'NotAllowedError',
      INVALID_STATE: 'InvalidStateError',
      NOT_FOUND: 'NotFoundError',
      NOT_SUPPORTED: 'NotSupportedError',
      CONSTRAINT: 'ConstraintError',
    },
    MESSAGES: {
      NOT_SUPPORTED: 'WebAuthn is not supported in this browser',
      USER_CANCELLED_AUTH: 'User cancelled authentication',
      USER_CANCELLED_REGISTRATION: 'User cancelled registration',
      NO_CREDENTIAL_FOUND: 'User cancelled authentication or no credential found',
      REGISTRATION_CANCELLED: 'User cancelled registration or credential creation failed',
      OPERATION_NOT_ALLOWED: 'The operation is not allowed',
      AUTHENTICATOR_ALREADY_HAS_CREDENTIAL:
        'This device already has a passkey registered. Platform authenticators can only store one passkey per account.',
      NOT_SUPPORTED_ERROR: 'WebAuthn is not supported',
      AUTHENTICATION_FAILED: 'Authentication failed',
      REGISTRATION_FAILED: 'Registration failed',
      UNSUPPORTED_RESPONSE_TYPE: 'Unsupported credential response type',
      CONSTRAINT_VALIDATION_FAILED: 'Constraint validation failed',
    },
    ERROR_PATTERNS: {
      USER_CANCELLED_AUTH: 'user cancelled authentication',
      NO_CREDENTIAL_FOUND: 'no credential found',
    },
  },
  SESSION: {
    SET_FAILED: 'Failed to save session token',
    REMOVE_FAILED: 'Failed to remove session token',
    QUOTA_EXCEEDED: 'Storage quota exceeded. Please free up space and try again.',
  },
  UI: {
    TITLE: 'Sign in to your account',
    SUBTITLE: 'Welcome back — choose your preferred method',
    EMAIL_PLACEHOLDER: 'Enter your email',
    BUTTON_LOADING: 'Authenticating...',
    BUTTON_SUBMIT: 'Authenticate',
    BUTTON_TEXT: 'Continue with Passkey',
    FOOTER_TEXT: "Don't have an account?",
    FOOTER_LINK: 'Create an account',
    GOOGLE_BUTTON_TEXT: 'Continue with Google',
    GOOGLE_BUTTON_LOADING: 'Redirecting to Google...',
    GOOGLE_OR_SEPARATOR: 'or',
    BRAND_NAME: 'telark',
    BRAND_LOGO_SRC: '/telark-logo.svg',
    BRAND_HEADLINE: 'A protection gate for your Kubernetes applications',
    BRAND_TAGLINE:
      'Decide what can change an application, and when. See every change that got through, and why an app broke.',
    BRAND_TAGLINE_ACCENT: 'Passkeys or Google sign-in. No passwords.',
  },
  OIDC: {
    GOOGLE_SCOPE: 'openid email',
    GOOGLE_RESPONSE_TYPE: 'id_token',
    GOOGLE_AUTH_URL: 'https://accounts.google.com/o/oauth2/v2/auth',
    STATE_STORAGE_KEY: 'telark:oidc:google:state',
    STATE_BYTES: 32,
    FRAGMENT_ID_TOKEN: 'id_token',
    FRAGMENT_STATE: 'state',
    CALLBACK_ERROR: 'Google login failed. Please try again.',
    CALLBACK_SUCCESS: 'Signed in with Google successfully.',
  },
  LOGS: {
    AUTH_ERROR: 'Authentication error:',
    INVALID_RESPONSE_STRUCTURE: 'Invalid login response structure:',
    SESSION_GET_ERROR: 'Failed to get session token:',
    SESSION_SET_ERROR: 'Failed to set session token:',
    SESSION_REMOVE_ERROR: 'Failed to remove session token:',
    SESSION_NAME_ERROR: 'Failed to derive session name:',
  },
} as const;
