import type { FormFieldConfig } from '../../../../interfaces/layout/modal';

export const USERS_CONSTANTS = {
  LABELS: {
    HEADER_TITLE: 'Users',
    HEADER_SUBTITLE: 'Manage existing users',
    VIEW_SUBTITLE: 'View user details',
    EDIT_SUBTITLE: 'Edit user details',
    CREATE_SUBTITLE: 'Create a new user',
    NOT_FOUND: 'User not found',
    UPDATE_BUTTON: 'Update User',
    CREATE_BUTTON: 'Add User',
    CREATE_BUTTON_TEXT: 'Add User',
    BREADCRUMBS: {
      USERS: 'Users',
      EDIT: 'Edit',
      CREATE: 'Add User',
    },
    MESSAGES: {
      CREATED: (name: string) => `User "${name}" created`,
      UPDATED: (name: string) => `User "${name}" updated`,
      DELETED: (name: string) => `User "${name}" deleted`,
      ROLE_ASSIGNED: (userName: string) => `Role assigned to "${userName}"`,
      GROUP_ASSIGNED: (userName: string) => `Group assigned to "${userName}"`,
      CREATE_FAILED: 'Failed to create user',
      UPDATE_FAILED: 'Failed to update user',
      DELETE_FAILED: 'Failed to delete user',
      ROLE_ASSIGN_FAILED: 'Failed to assign role',
      GROUP_ASSIGN_FAILED: 'Failed to assign group',
      ROLE_DEASSIGNED: (roleName: string) => `Role "${roleName}" was removed`,
      ROLE_DEASSIGN_FAILED: 'Failed to remove role',
      GROUP_DEASSIGNED: (groupName: string) => `Group "${groupName}" was removed`,
      GROUP_DEASSIGN_FAILED: 'Failed to remove group',
      NO_ASSIGNED_GROUPS: 'No groups assigned yet',
      NO_USERS_TITLE: 'No users yet',
      NO_USERS_DESCRIPTION: 'Get started by adding your first user to the system.',
      NO_ROLES_AVAILABLE: 'No roles available',
      NO_GROUPS_AVAILABLE: 'No groups available',
      NO_ASSIGNED_ROLES: 'No roles assigned yet',
      NO_GROUP_ROLES: 'No roles inherited from groups',
      ROLE_INHERITED_FROM_GROUP: (groupNames: string) =>
        `Already granted via group: ${groupNames}`,
      LOADING_ROLES: 'Loading roles...',
      LOADING_GROUPS: 'Loading groups...',
    },
    VALIDATION: {
      USERNAME_TAKEN: 'Username is already taken',
      INVALID_EMAIL: 'Please enter a valid email address',
      FULLNAME_SPECIAL_CHARS: 'Full name must not contain special characters',
    },
    COLUMNS: {
      USERNAME: 'Username',
      FULLNAME: 'Full Name',
      EMAIL: 'Email',
      ROLES: 'Roles',
      CREATED: 'Creation Date',
    },
    VIEW_LABELS: {
      USERNAME: 'Username',
      FULLNAME: 'Full Name',
      EMAIL: 'Email',
      ROLES: 'Roles',
      GROUPS: 'Groups',
      STATUS: 'Status',
      CREATION_DATE: 'Creation Date',
    },
    ACTIONS: {
      VIEW: 'View',
      EDIT: 'Edit',
      DELETE: 'Delete',
      MANAGE_ROLES: 'Manage Roles',
      MANAGE_GROUPS: 'Manage Groups',
      DELETE_MODAL_TITLE: 'Delete User',
      DELETE_MODAL_CONTENT: (name: string) => `Are you sure you want to delete "${name}"?`,
      DELETE_MODAL_OK: 'Delete',
      DEASSIGN_ROLE_MODAL_TITLE: 'Remove Role',
      DEASSIGN_ROLE_MODAL_ACTION: 'Remove',
      DEASSIGN_ROLE_MODAL_CONFIRM: 'Remove',
      DEASSIGN_ROLE_RESOURCE_TYPE: 'role',
      DEASSIGN_GROUP_MODAL_TITLE: 'Remove Group',
      DEASSIGN_GROUP_MODAL_ACTION: 'Remove',
      DEASSIGN_GROUP_MODAL_CONFIRM: 'Remove',
      DEASSIGN_GROUP_RESOURCE_TYPE: 'group',
      BULK_DELETE: 'Bulk Delete',
      BULK_DELETE_MODAL_TITLE: 'Delete Users',
      BULK_DELETE_LOADING: (count: number) =>
        `Deleting ${count} user${count > 1 ? 's' : ''}...`,
      BULK_DELETE_SUCCESS: (count: number) =>
        `${count} user${count > 1 ? 's' : ''} deleted successfully`,
      BULK_DELETE_FAILED: 'Failed to delete some users',
    },
    FILTER: {
      LABELS: {
        BY_CREATION_DATE: 'By creation date',
        BY_STATUS: 'By status',
        FROM: 'From',
        TO: 'To',
      },
      STATUS_OPTIONS: {
        ALL: 'All',
        ACTIVE: 'Active',
        INACTIVE: 'Inactive',
      },
    },
    FORM: {
      TITLE: 'Add User',
      SUBTITLE: 'Add a new user',
      SECTION_TITLE: 'User Details',
      SECTION_SUBTITLE: 'Provide the user information.',
      BUTTON_TEXT: 'Add User',
      SECTIONS: {
        USER_DETAILS: 'User Details',
        ASSIGNMENT: 'Assignment',
      },
      FIELDS: {
        AVATAR_LABEL: 'Avatar',
        USERNAME_LABEL: 'Username',
        USERNAME_PLACEHOLDER: 'e.g. john.doe',
        FULLNAME_LABEL: 'Full Name',
        FULLNAME_PLACEHOLDER: 'e.g. John Doe',
        EMAIL_LABEL: 'Email',
        EMAIL_PLACEHOLDER: 'e.g. john.doe@example.com',
        ROLE_LABEL: 'Role',
        ROLE_PLACEHOLDER: 'Select a role',
        GROUP_LABEL: 'Group',
        GROUP_PLACEHOLDER: 'Select a group',
      },
    },
    PANELS: {
      VIEW: {
        TITLE: 'User Details',
      },
      EDIT: {
        TITLE: 'Edit User',
        SUBTITLE: (name: string) => `Edit information for ${name}`,
        SUBMIT_BUTTON: 'Update User',
      },
      CREATE: {
        TITLE: 'Add User',
        SUBTITLE: 'Add a new user to the system',
        SUBMIT_BUTTON: 'Add User',
      },
      MANAGE_ROLE: {
        TITLE: 'Manage Roles',
        SUBTITLE: (userName: string) => `View and manage roles for ${userName}`,
        SUBMIT_BUTTON: 'Update roles',
        SEARCH_PLACEHOLDER: 'Search roles by name or description...',
        SHOW_ASSIGNED_BUTTON: 'Assigned',
        SHOW_ASSIGNED_TOOLTIP: 'View all roles currently assigned to this user, including inherited ones from groups',
        FROM_GROUPS_BUTTON: 'From Groups',
        FROM_GROUPS_TOOLTIP: 'View roles this user inherits through their assigned groups',
      },
      MANAGE_GROUP: {
        TITLE: 'Manage Groups',
        SUBTITLE: (userName: string) => `View and manage groups for ${userName}`,
        SUBMIT_BUTTON: 'Update groups',
        SEARCH_PLACEHOLDER: 'Search groups by name or description...',
        SHOW_ASSIGNED_BUTTON: 'Assigned',
        SHOW_ASSIGNED_TOOLTIP: 'View all groups currently assigned to this user',
      },
    },
    TOOLBAR: {
      SEARCH: {
        PLACEHOLDER: 'Search users by name, email...',
        BUTTON_LABEL: 'Search',
      },
      FILTER: {
        BUTTON_LABEL: 'Filter',
      },
      CREATE: {
        BUTTON_LABEL: 'Add User',
      },
      MANAGE: {
        BUTTON_LABEL: 'Manage',
        ITEMS: {
          MANAGE_ROLES: 'Manage Roles',
          MANAGE_GROUPS: 'Manage Groups',
        },
      },
    },
    EMPTY: {
      NO_USERS_FOUND: 'No Users Found',
    },
    PAGINATION: {
      SHOW_ROWS: 'Show rows',
    },
    MODAL: {
      CANCEL: 'Cancel',
    },
    LOGS: {
      FETCH_USERS: 'Fetching users',
    },
  },
  KEYS: {
    USERNAME: 'username',
    FULLNAME: 'fullname',
    EMAIL: 'email',
    ROLES: 'assignedRolesIDs',
    CREATION_DATE: 'creationDate',
    ACTIONS: 'actions',
  } as const,
  SIZES: {
    ROW_HEIGHT: 32,
    HEADER_ICON: 14,
    CHIP_FONT: 12,
    COLUMNS: {
      USERNAME: 150,
      FULLNAME: 180,
      EMAIL: 220,
      ROLE: 120,
      CREATED: 120,
      ACTIONS: 50,
    },
    MODAL_WIDTH: 360,
  },
  FORM: {
    FIELDS: [
      {
        type: 'input',
        name: 'username',
        label: 'Username',
        placeholder: 'e.g. john.doe',
        required: true,
        marginBottom: 18,
      },
      {
        type: 'input',
        name: 'fullname',
        label: 'Full Name',
        placeholder: 'e.g. John Doe',
        required: true,
        marginBottom: 18,
      },
      {
        type: 'input',
        name: 'email',
        label: 'Email',
        placeholder: 'e.g. john.doe@example.com',
        required: true,
        marginBottom: 18,
      },
      {
        type: 'select',
        name: 'role',
        label: 'Role',
        placeholder: 'Select a role',
        required: true,
        options: [
          { label: 'Admin', value: 'Admin' },
          { label: 'Viewer', value: 'Viewer' },
          { label: 'Contributor', value: 'Contributor' },
          { label: 'Ops Engineer', value: 'Ops Engineer' },
          { label: 'Platform Admin', value: 'Platform Admin' },
        ],
        marginBottom: 6,
      },
    ] as FormFieldConfig[],
    INITIAL_VALUES: {
      role: 'Viewer',
    },
  },
} as const;

export type UsersConstants = typeof USERS_CONSTANTS;
