export const APPLICATIONS_UI = {
  HEADER_TITLE: 'Applications',
  HEADER_SUBTITLE:
    'Workloads grouped into applications automatically. Check health, see what changed, and roll back.',
  DISCOVERY_IN_PROGRESS: (remaining: number) =>
    remaining > 0
      ? `Discovering applications: ${remaining} left to refresh. New applications appear as the scan completes.`
      : 'Discovering applications. New applications appear as the scan completes.',
  DISCOVERY_IDLE: 'Applications up to date.',
  TOOLBAR_SEARCH_PLACEHOLDER: 'Search applications by name, status, or display name...',
  TOOLBAR_SEARCH_BUTTON: 'Search',
  TOOLBAR_CLEAR_ALL: 'Clear All',
  TOOLBAR_BULK_SELECT: 'Bulk',
  TOOLBAR_BULK_SELECT_ACTIVE: 'Exit bulk',
  TOOLBAR_SELECT_ALL: 'Select all on page',
  // Measured natural widths of the toolbar row: ~984px in bulk mode (select-all
  // cluster + pills + actions) and ~621px otherwise: the icon-only view control
  // adds TOOLBAR_CONTROL.HEIGHT + TOOLBAR_ITEM_GAP. Below these the controls
  // fall back to icons instead of overflowing into a scroll.
  TOOLBAR_COMPACT_WIDTH: {
    BULK: 1040,
    DEFAULT: 676,
  },
  TOOLBAR_HEALTH_FILTER: 'Filter by health',
  TOOLBAR_HEALTH_OPTIONS: {
    ALL: 'All',
    HEALTHY: 'Healthy',
    DEGRADED: 'Degraded',
    UNHEALTHY: 'Unhealthy',
  },
  TOOLBAR_BULK_FORCE_SYNC: 'Force Sync',
  TOOLBAR_BULK_RESET: 'Reset',
  TOOLBAR_BULK_RESET_CONFIRM_TITLE: 'Reset selected applications?',
  TOOLBAR_BULK_RESET_CONFIRM_MESSAGE:
    'Resetting clears the history, snapshots and rollbacks of the selected applications. Kubernetes resources in your cluster are not touched. The applications are rediscovered on the next scan.',
  TOOLBAR_COUNT_SUFFIX: { one: 'app', other: 'apps' },
  TOOLBAR_MORE_LABEL: 'More',
  NO_MATCH_TITLE: 'No matching applications',
  NO_MATCH_DESCRIPTION: 'No applications match the current search and filters.',
  CLEAR_ALL_FILTERS: 'Clear all filters',
  FILTER: {
    BY_STATUS: 'Status',
    BY_MANAGED_BY: 'Managed by',
    BY_MANAGED_CHART: 'Managed chart',
    BY_NAMESPACE: 'Namespaces',
    BY_CR_STATUS: 'CR status',
    BY_HAS_DRIFT: 'Has drift',
    BY_CREATION_DATE: 'Created date',
    FROM: 'From',
    TO: 'To',
    OPTION_YES: 'Yes',
    OPTION_NO: 'No',
  },
  BREADCRUMBS: {
    ROOT: 'Applications',
  },
  DETAIL_PAGE: {
    SUBTITLE: 'Health, resources, change history, and snapshots you can roll back to.',
  },
  EDIT_PAGE: {
    PANEL_TITLE: 'Edit application',
    SUCCESS_MESSAGE: 'Application updated.',
    SECTION_BASIC: 'Basic information',
    SECTION_BASIC_DESC: 'Name, display name, and description.',
    SAVE: 'Save changes',
    NAME_LABEL: 'Application name',
    DISPLAY_NAME_LABEL: 'Display name',
    DESCRIPTION_LABEL: 'Description',
    ERROR_GENERIC: 'Could not save changes. Please try again.',
    TOO_LONG: (max: number) => `Use at most ${max} characters.`,
  },
  FALLBACKS: {
    UNKNOWN: 'unknown',
  },
  SECTIONS: {
    OVERVIEW: {
      TITLE: 'Application summary',
      DESCRIPTION: 'Core application metadata, health, history, and runtime configuration.',
      COMBINED_SUBTITLE: 'Core metadata, history, and runtime configuration.',
      COLUMN_PRIMARY: 'Status & metadata',
      COLUMN_RUNTIME: 'Runtime',
      REPLICAS: 'Replicas',
      DEPLOYED_IN: 'Deployed in',
      GROUP_HISTORY_META: 'History and drift',
      MANAGED_CHART: 'Managed chart',
      MANAGED_VERSION: 'Managed version',
      HISTORY_GENERATION: 'History generation',
      HAS_DRIFT: 'Has drift',
      LAST_MODIFIED_BY: 'Last modified by',
      LAST_MODIFIED_AT: 'Last modified at',
    },
    RESOURCE_SUMMARY: {
      TITLE: 'Resource summary',
      DESCRIPTION: 'Resource kind counts detected for this application.',
      EMPTY: 'No resources attached.',
    },
    NAMESPACES: {
      TITLE: 'Namespaces',
      DESCRIPTION: 'Namespaces associated with this application.',
    },
    DETAILS_TOOLBAR: {
      MORE_LABEL: 'More',
      MORE_TOOLTIP: 'More actions',
      SYNCED_PREFIX: 'synced',
      NEVER_SYNCED: 'never synced',
      SEPARATOR: '·',
    },
    RESOURCES: {
      TITLE: 'Resources',
      DESCRIPTION: 'Resources discovered for this application.',
      SHOWING_FIRST: 'Showing first',
      VIEW_GRAPH: 'Graph',
      VIEW_TREE: 'Tree',
      VIEW_GRAPH_TOOLTIP: 'Radial view',
      VIEW_TREE_TOOLTIP: 'Structure view',
    },
    RUNTIME: {
      TITLE: 'Runtime',
      DESCRIPTION: 'Ports, images, and environment variable keys.',
      PORTS: 'Ports',
      IMAGES: 'Images',
      ENV_VAR_KEYS: 'Environment variables',
    },
    SNAPSHOTS: {
      TITLE: 'Snapshots',
      DESCRIPTION: 'Stored snapshots detected for this application.',
      SHOWING_FIRST: 'Showing first',
      EMPTY_TITLE: 'No snapshots yet',
      EMPTY_DESCRIPTION: 'No snapshots have been taken for this application.',
      ROLLBACKS_EMPTY_TITLE: 'No rollbacks yet',
      ROLLBACKS_EMPTY_DESCRIPTION: 'No rollbacks have been triggered for this application.',
      GENERATION: 'Generation',
      SEVERITY: 'Severity',
      SIZE: 'Size',
      RESTORED_PREFIX: 'Restored',
      // "Generation N" alone reads as the rollback's own generation. This says
      // which snapshot it went back to.
      ROLLBACK_TARGET_PREFIX: 'Rolled back to generation',
      BY_PREFIX: 'by',
      TRIGGERED_PREFIX: 'Triggered',
      COMPLETED_PREFIX: 'Completed',
      META_SEPARATOR: '·',
      SHOW_ERROR: 'Why did this fail?',
      HIDE_ERROR: 'Hide details',
      STORAGE_AVAILABLE: 'Available',
      STORAGE_TOTAL: 'Total',
      STORAGE_METRICS_JOINER: ' · ',
      COMPARE_LOADING: 'Loading manifest…',
      COMPARE_IDENTICAL: 'These two snapshots are identical.',
      COMPARE_CHANGE: 'change',
      COMPARE_FROM_LABEL: 'Baseline',
      COMPARE_TO_LABEL: 'Compared with',
      COMPARE_STAT_CHANGES: 'Changes',
      COMPARE_STAT_RESOURCES: 'Resources',
      COMPARE_STAT_ADDED: 'Added',
      COMPARE_STAT_REMOVED: 'Removed',
      COMPARE_STAT_MODIFIED: 'Modified',
      COMPARE_BEFORE: 'Before',
      COMPARE_AFTER: 'After',
      COMPARE_ADDED_CHIP: 'added',
      COMPARE_REMOVED_CHIP: 'removed',
      COMPARE_IDENTICAL_TITLE: 'No differences',
      COMPARE_NO_VISIBLE_TITLE: 'No visible differences',
      COMPARE_IDENTICAL_REDACTED: 'Secret values are redacted, so changes to them are not shown.',
      COMPARE_ERROR_TITLE: 'Comparison unavailable',
      COMPARE_RESOURCE_ADDED: 'Resource present only in the compared snapshot',
      COMPARE_RESOURCE_REMOVED: 'Resource present only in the baseline snapshot',
      COMPARE_REDACTED: '••••••',
      COMPARE: 'Compare',
      VIEW_MANIFEST: 'View Manifest',
      ROLLBACK: 'Rollback',
      ROLLBACK_CONFIRM_TITLE: 'Roll back to this snapshot?',
      ROLLBACK_CONFIRM_CONTENT:
        'Once a rollback starts, it cannot be aborted, so you get a short undo window before it is sent.',
      ROLLBACK_CONFIRM_OK: 'Start rollback',
      ROLLBACK_COUNTDOWN_CONTENT:
        'Undo now if you need more time. Once the rollback starts it cannot be aborted.',
      ROLLBACK_UNDO: 'Undo',
      ROLLBACK_SUCCESS: 'Rollback request submitted.',
      ROLLBACK_FAILED: 'Rollback could not be started. Please try again.',
      ROLLBACK_USER_REQUIRED: 'Sign in with a user account to start a rollback.',
      TAKEN_AT: 'Taken at',
      MANIFEST_MODAL_TITLE: 'Manifest',
      MANIFEST_BACK: 'Snapshots',
      MANIFEST_BACK_TOOLTIP: 'Back to snapshots',
      MANIFEST_TAB_JSON: 'JSON',
      MANIFEST_TAB_YAML: 'YAML',
      MANIFEST_COPY_TOOLTIP: 'Copy to clipboard',
      MANIFEST_COPIED: 'Copied',
      MANIFEST_COPY_FAILED: 'Failed to copy',
      MANIFEST_LOADING: 'Loading manifest…',
      MANIFEST_NOT_FOUND_TITLE: 'Manifest not available',
      MANIFEST_NOT_FOUND_DESCRIPTION:
        'This snapshot has no stored manifest. Snapshot retention may have removed it, or it was never captured.',
      MANIFEST_ERROR_TITLE: 'Could not load the manifest',
      MANIFEST_ERROR_DESCRIPTION: 'The manifest could not be read. Try again in a moment.',
      MANIFEST_EMPTY_TITLE: 'Nothing to show',
      MANIFEST_EMPTY_DESCRIPTION: 'This snapshot has an empty manifest.',
      MANIFEST_SHOW_DETAILS: 'Technical details',
      MANIFEST_HIDE_DETAILS: 'Hide details',
      VIEW_MANIFEST_PERMISSION_DENIED_TOOLTIP:
        'You do not have permission to view snapshot manifests',
      ROLLBACK_FILE_MISSING_TOOLTIP:
        'This snapshot is no longer stored, so you cannot roll back to it.',
      VIEW_MANIFEST_FILE_MISSING_TOOLTIP:
        'This snapshot is no longer stored, so its manifest cannot be shown.',
      ROLLBACK_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to roll back applications',
      ROLLBACK_IN_PROGRESS_TOOLTIP:
        'Unavailable while a rollback is pending or running for this application.',
      ABORT_ROLLBACK: 'Abort rollback',
      ABORT_ROLLBACK_TOOLTIP: 'Abort this pending rollback',
      ABORT_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to abort rollbacks',
      ABORT_CONFIRM_TITLE: 'Abort rollback?',
      ABORT_CONFIRM_CONTENT: 'This rollback has not started yet. Aborting cancels it permanently.',
      ABORT_CONFIRM_OK: 'Abort rollback',
      ABORT_SUCCESS: 'Rollback aborted.',
      ABORT_FAILED: 'Could not abort rollback. Please try again.',
    },
    METRICS: {
      TITLE: 'Metrics',
      DESCRIPTION: 'Derived change metrics for this application.',
      TIMELINE: 'Timeline',
      TOTAL_CHANGES: 'Total changes',
      SNAPSHOT_COUNT: 'Snapshot count',
      UNIQUE_FINGERPRINTS: 'Unique fingerprints',
      CHANGE_VELOCITY: 'Change velocity/day',
      FIRST_CHANGE: 'First change detected',
      LAST_CHANGE: 'Last change detected',
      TOTAL_INCIDENTS: 'Total incidents',
      TOTAL_RECOVERIES: 'Total recoveries',
      CHANGES_BY_CLASS: 'Changes by class',
      CHANGES_BY_SEVERITY: 'Changes by severity',
    },
    WORKLOAD_METRICS: {
      TITLE: 'Workload metrics',
      DESCRIPTION: 'Per-workload baseline and usage (when available).',
      USAGE_EMPTY: 'Usage data is not available for this workload yet.',
      OF_REQUEST: 'of request',
      OF_LIMIT: 'of limit',
      NO_BASELINE: 'no request set',
      REPLICAS_SUFFIX: { one: 'replica', other: 'replicas' },
      INSTANCES_TITLE: 'Pods',
      POD_LABEL: 'Pod',
      CONTAINERS_LABEL: 'Containers running in this pod',
      POD_TOTAL_LABEL: 'pod total',
      POD_TOTAL_TOOLTIP: 'Sum of every container running in this pod.',
      LIMIT_TICK_TOOLTIP: 'Limit',
      SHOWING_FIRST_INSTANCES: 'Showing first 3 pods of',
      CPU_ABBREV: 'CPU',
      MEMORY_ABBREV: 'Mem',
      MID_DOT: '·',
      MORE_CONTAINERS_SUFFIX: 'more containers',
      RESOURCE_CPU_LABEL: 'CPU',
      RESOURCE_MEMORY_LABEL: 'Memory',
    },
    CHANGE_LOG: {
      TITLE: 'History Changes',
      DESCRIPTION: 'Detected changes and incidents.',
      SHOWING_FIRST: 'Showing first',
      GEN: 'Generation',
      SEVERITY: 'severity',
      BY_PREFIX: 'By',
      SNAPSHOT_AVAILABLE: 'snapshot',
      SNAPSHOT_MISSING: 'no snapshot',
      SNAPSHOT_AVAILABLE_TOOLTIP:
        'A pre-change snapshot is stored for this generation. You can compare it or roll back to it.',
      SNAPSHOT_MISSING_TOOLTIP:
        'Removed by the per-application snapshot limit. The entry stays in the history, but you can no longer compare it or roll back to it.',
      MORE_CHANGES: 'more',
      SCROLL_FOR_MORE_TOOLTIP: 'Scroll to see the remaining changes',
      // The API appends the target snapshot id to the rollback description
      // ("... generation 1 snapshot snap-3415eeaa"). The id is already the
      // change's newValue and adds nothing to the sentence.
      ROLLBACK_SNAPSHOT_JOINER: ' snapshot ',
      DIFF_ARROW: '→',
      EMPTY_TITLE: 'No history yet',
      EMPTY_DESCRIPTION: 'No history recorded for this application yet.',
    },
  },
  CARD: {
    LABELS: {
      NAME: 'Name',
      NAMESPACE: 'Namespace',
      STATUS: 'Status',
      HEALTH: 'Health',
      NAMESPACES: 'Namespaces',
      RESOURCES: 'Resources',
      WORKLOADS: 'Workloads',
      MANAGED_BY: 'Managed by',
      LAST_UPDATED: 'Last updated',
      CREATED_AT: 'Created at',
      PUBLISHED: 'Published',
      RUNTIME: 'Runtime',
      FOOTER_NAMESPACE: 'Namespace',
      FOOTER_MANAGED: 'Managed by',
      RUNTIME_CHIPS: {
        PORTS: 'ports',
        IMAGES: 'images',
        ENV_KEYS: 'env keys',
      },
    },
    ACTIONS: {
      VIEW: 'View',
      EDIT: 'Edit',
      FORCE_SYNC: 'Force Sync',
      MANAGE_SNAPSHOTS: 'Manage Snapshots',
      MANAGE_ROLLBACKS: 'Manage Rollbacks',
      SYNC_DISABLED_TOOLTIP: 'Unavailable while a sync is in progress.',
      EDIT_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to edit applications',
      FORCE_SYNC_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to sync applications',
      FORCE_SYNC_FAILED: 'Force sync request failed.',
      RESET_FAILED: 'Could not reset the application.',
      VIEW_SNAPSHOTS_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to view snapshots',
      VIEW_ROLLBACKS_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to view rollbacks',
      RESET_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to reset applications',
      CANCEL: 'Cancel',
      RESET: 'Reset',
      RESET_CONFIRM_TITLE: 'Reset application?',
      RESET_CONFIRM_CONTENT: 'This action cannot be undone.',
      RESET_CONFIRM_MESSAGE:
        'Resetting clears the history, snapshots and rollbacks of this application. Kubernetes resources in your cluster are not touched. The application is rediscovered on the next scan.',
      ROLLBACKS_PLACEHOLDER: 'Rollbacks are managed from the snapshots section.',
    },
    SYNC_STATUS: {
      SYNCING: 'Syncing',
      SUCCESS: 'Synced',
      FAILED: 'Sync failed',
    },
  },
} as const;
