import { DEFAULT_COLORS } from '../../../../constants';
import { SETTINGS_CONSTANTS } from '../../../settings/constants';

/** Applications feature: spacing and dividers aligned with settings/content tokens. */
export const APPLICATION_SECTION_LAYOUT = {
  STACK_GAP_PX: SETTINGS_CONSTANTS.CONTENT.GAP_BETWEEN_CARDS,
  CARD_RADIUS: SETTINGS_CONSTANTS.CONTENT.CARD_BORDER_RADIUS,
  CARD_PADDING: SETTINGS_CONSTANTS.CONTENT.CARD_PADDING,
  TITLE_TO_SUBTITLE_GAP_PX: SETTINGS_CONSTANTS.CONTENT.CARD_TITLE_TO_DESCRIPTION_GAP_PX,
  FIELD_LABEL_FONT_SIZE: 11,
  FIELD_VALUE_FONT_SIZE: 13,
  COLUMN_HEADER_FONT_SIZE: 12,
  SUBTLE_DIVIDER: `1px solid ${DEFAULT_COLORS.BORDER_LIGHT}`,
  COLUMN_INNER_RADIUS: SETTINGS_CONSTANTS.CONTENT.CARD_BORDER_RADIUS,
  TAG_CLOUD_MAX_HEIGHT_PX: 120,
  STAT_MIN_WIDTH_PX: 120,
  /** RowTag display for runtime list values (ports, env keys, snapshot field tags). */
  RUNTIME_VALUE_ROW_TAG: {
    background: DEFAULT_COLORS.CHIP_CUSTOM_BG,
    color: DEFAULT_COLORS.CHIP_CUSTOM_TEXT,
    fontSize: 11,
  },
} as const;
