export const APPLICATIONS_UI = {
  HEADER_TITLE: 'Applications',
  HEADER_SUBTITLE: 'Inspect application health, resources, insights, and change history.',
  TOOLBAR_SEARCH_PLACEHOLDER: 'Search applications by name, status, or display name...',
  TOOLBAR_SEARCH_BUTTON: 'Search',
  BREADCRUMBS: {
    ROOT: 'Applications',
    EDIT: 'Edit',
  },
  DETAIL_PAGE: {
    SUBTITLE: 'Application details, resources, metrics, and change history.',
  },
  EDIT_PAGE: {
    SUBTITLE: 'Update application metadata and configuration.',
    SUCCESS_MESSAGE: 'Application updated successfully.',
    SECTION_BASIC: 'Basic information',
    SECTION_BASIC_DESC: 'Name, display name, description, and primary namespace.',
    SECTION_WORKLOAD: 'Workload configuration',
    SECTION_WORKLOAD_DESC: 'Optional notes for workload-related settings.',
    SAVE: 'Save changes',
    NAME_LABEL: 'Application name',
    DISPLAY_NAME_LABEL: 'Display name',
    DESCRIPTION_LABEL: 'Description',
    NAMESPACE_LABEL: 'Primary namespace',
    WORKLOAD_CONFIG_LABEL: 'Workload configuration',
    WORKLOAD_CONFIG_PLACEHOLDER: 'Optional configuration notes',
    ERROR_GENERIC: 'Could not save changes. Please try again.',
  },
  FALLBACKS: {
    UNKNOWN: 'unknown',
    EMPTY: '—',
    NOT_ENRICHED: 'Not enriched.',
  },
  SECTIONS: {
    OVERVIEW: {
      TITLE: 'Overview',
      DESCRIPTION: 'Core application metadata and health.',
      COMBINED_SUBTITLE: 'Core metadata, resource summary, and runtime configuration.',
      COLUMN_PRIMARY: 'Overview',
      COLUMN_RESOURCES: 'Resources',
      COLUMN_RUNTIME: 'Runtime',
      REPLICAS: 'Replicas',
      REPLICAS_READY: 'Replicas ready',
      GROUP_PRIMARY_META: 'Status and lifecycle',
      GROUP_HISTORY_META: 'History and drift',
      MANAGED_CHART: 'Managed chart',
      MANAGED_VERSION: 'Managed version',
      HISTORY_GENERATION: 'History generation',
      HAS_DRIFT: 'Has drift',
      LAST_MODIFIED_BY: 'Last modified by',
      LAST_MODIFIED_AT: 'Last modified at',
    },
    RESOURCE_SUMMARY: {
      TITLE: 'Resource summary',
      DESCRIPTION: 'Resource kind counts detected for this application.',
      EMPTY: 'No resources attached.',
    },
    NAMESPACES: {
      TITLE: 'Namespaces',
      DESCRIPTION: 'Namespaces associated with this application.',
    },
    RESOURCES: {
      TITLE: 'Resources',
      DESCRIPTION: 'Resources discovered for this application.',
      SHOWING_FIRST: 'Showing first',
    },
    INSIGHTS: {
      TITLE: 'Insights',
      DESCRIPTION: 'Enrichment results and suggestions (if available).',
      EMPTY_TITLE: 'No insights available',
      EMPTY_DESCRIPTION: 'No insights are available for this application yet.',
      ENRICHMENT_HINT:
        'Enrichment adds category, role, stack context, and suggestions when data is available from the platform.',
      CONFIDENCE: 'Confidence',
      CATEGORY: 'Category',
      ROLE: 'Role',
      ENRICHED_AT: 'Enriched at',
      DEPENDENCIES: 'Dependencies',
      RISKS: 'Risks',
      SUGGESTIONS: 'Suggestions',
      RELATED_APPS: 'Related apps',
      PROMPT_VERSION: 'Prompt version',
    },
    RUNTIME: {
      TITLE: 'Runtime',
      DESCRIPTION: 'Ports, images, and environment variable keys.',
      PORTS: 'Ports',
      IMAGES: 'Images',
      ENV_VAR_KEYS: 'Env var keys',
    },
    SNAPSHOTS: {
      TITLE: 'Snapshots',
      DESCRIPTION: 'Stored snapshots detected for this application.',
      SHOWING_FIRST: 'Showing first',
      EMPTY_TITLE: 'No snapshots yet',
      EMPTY_DESCRIPTION: 'No snapshots available yet for this application.',
      SNAPSHOT_ID: 'Snapshot ID',
      SIZE: 'Size',
      STORAGE_AVAILABLE: 'Available',
      STORAGE_TOTAL: 'Total',
      STORAGE_METRICS_JOINER: ' · ',
      VIEW_MANIFEST: 'View Manifest',
      ROLLBACK: 'Rollback',
      MANIFEST_MODAL_TITLE: 'Manifest',
    },
    METRICS: {
      TITLE: 'Metrics',
      DESCRIPTION: 'Derived change metrics for this application.',
      TIMELINE: 'Timeline',
      TOTAL_CHANGES: 'Total changes',
      SNAPSHOT_COUNT: 'Snapshot count',
      UNIQUE_FINGERPRINTS: 'Unique fingerprints',
      CHANGE_VELOCITY: 'Change velocity/day',
      FIRST_CHANGE: 'First change detected',
      LAST_CHANGE: 'Last change detected',
      TOTAL_INCIDENTS: 'Total incidents',
      TOTAL_RECOVERIES: 'Total recoveries',
      CHANGES_BY_CLASS: 'Changes by class',
      CHANGES_BY_SEVERITY: 'Changes by severity',
    },
    WORKLOAD_METRICS: {
      TITLE: 'Workload metrics',
      DESCRIPTION: 'Per-workload baseline and usage (when available).',
      USAGE_EMPTY: 'Usage data is not available for this workload yet.',
      BASELINE: 'Baseline',
      USAGE: 'Usage',
      FINGERPRINT: 'Fingerprint',
      REPLICAS: 'Replicas',
      REQUESTS: 'Requests',
      LIMITS: 'Limits',
      QOS: 'QoS',
      TOTAL_CPU: 'Total CPU',
      TOTAL_MEMORY: 'Total memory',
      NOT_AVAILABLE: 'Not available.',
      SHOWING_FIRST_INSTANCES: 'Showing first 3 instances of',
    },
    CHANGE_LOG: {
      TITLE: 'History Changes',
      DESCRIPTION: 'Detected changes and incidents.',
      SHOWING_FIRST: 'Showing first',
      GEN: 'Gen',
      BY_PREFIX: 'By',
      DIFF_ARROW: '→',
      EMPTY_TITLE: 'No history yet',
      EMPTY_DESCRIPTION: 'No history recorded for this application yet.',
    },
  },
  CARD: {
    LABELS: {
      NAME: 'Name',
      NAMESPACE: 'Namespace',
      STATUS: 'Status',
      HEALTH: 'Health',
      NAMESPACES: 'Namespaces',
      RESOURCES: 'Resources',
      WORKLOADS: 'Workloads',
      MANAGED_BY: 'Managed by',
      LAST_UPDATED: 'Last updated',
      CREATED_AT: 'Created at',
      CR_STATUS: 'CR status',
      RUNTIME: 'Runtime',
      FOOTER_NAMESPACE: 'Namespace',
      FOOTER_MANAGED: 'Managed by',
      RUNTIME_CHIPS: {
        PORTS: 'ports',
        IMAGES: 'images',
        ENV_KEYS: 'env keys',
      },
    },
    ACTIONS: {
      VIEW: 'View',
      EDIT: 'Edit',
      MANAGE_ROLLBACKS: 'Manage Rollbacks',
      CANCEL: 'Cancel',
      DELETE: 'Delete',
      DELETE_CONFIRM_TITLE: 'Delete application?',
      DELETE_CONFIRM_CONTENT: 'This action cannot be undone.',
      ROLLBACKS_PLACEHOLDER: 'Rollbacks are managed from the snapshots section.',
    },
  },
} as const;
