export const APPLICATIONS_UI = {
  HEADER_TITLE: 'Applications',
  HEADER_SUBTITLE: 'Inspect application health, resources, snapshots, and more.',
  TOOLBAR_SEARCH_PLACEHOLDER: 'Search applications by name, status, or display name...',
  TOOLBAR_SEARCH_BUTTON: 'Search',
  TOOLBAR_CLEAR_ALL: 'Clear All',
  TOOLBAR_BULK_SELECT: 'Bulk',
  TOOLBAR_BULK_SELECT_ACTIVE: 'Exit bulk',
  TOOLBAR_SELECT_ALL: 'Select all on page',
  // Measured natural widths of the toolbar row: ~984px in bulk mode (select-all
  // cluster + pills + actions) and ~585px otherwise. Below these the controls
  // fall back to icons instead of overflowing into a scroll.
  TOOLBAR_COMPACT_WIDTH: {
    BULK: 1040,
    DEFAULT: 640,
  },
  TOOLBAR_HEALTH_FILTER: 'Filter by health',
  TOOLBAR_HEALTH_OPTIONS: {
    ALL: 'All',
    HEALTHY: 'Healthy',
    DEGRADED: 'Degraded',
    UNHEALTHY: 'Unhealthy',
  },
  TOOLBAR_BULK_FORCE_SYNC: 'Force Sync',
  TOOLBAR_BULK_DELETE: 'Delete',
  TOOLBAR_BULK_DELETE_CONFIRM_TITLE: 'Delete selected applications?',
  TOOLBAR_BULK_DELETE_CONFIRM_MESSAGE:
    'Deleting selected applications removes only their platform definitions. Kubernetes resources in your cluster are not deleted.',
  TOOLBAR_LAYOUT_SINGLE: 'Focus view',
  TOOLBAR_LAYOUT_DOUBLE: 'Compare view',
  TOOLBAR_COUNT_SUFFIX: 'apps',
  TOOLBAR_MORE_LABEL: 'More',
  FILTER: {
    BY_STATUS: 'STATUS',
    BY_MANAGED_BY: 'MANAGED BY',
    BY_MANAGED_CHART: 'MANAGED CHART',
    BY_NAMESPACE: 'NAMESPACES',
    BY_INSIGHT_CATEGORY: 'INSIGHT CATEGORY',
    BY_INSIGHT_ROLE: 'INSIGHT ROLE',
    BY_CR_STATUS: 'CR STATUS',
    BY_HAS_DRIFT: 'HAS DRIFT',
    BY_CREATION_DATE: 'CREATED DATE',
    FROM: 'From',
    TO: 'To',
    OPTION_YES: 'Yes',
    OPTION_NO: 'No',
  },
  BREADCRUMBS: {
    ROOT: 'Applications',
  },
  DETAIL_PAGE: {
    SUBTITLE: 'Inspect application health, resources, snapshots, and more.',
  },
  EDIT_PAGE: {
    PANEL_TITLE: 'Edit application',
    SUBTITLE: 'Update application display name and description.',
    SUCCESS_MESSAGE: 'Application updated successfully.',
    SECTION_BASIC: 'Basic information',
    SECTION_BASIC_DESC: 'Name, display name, and description.',
    SAVE: 'Save changes',
    NAME_LABEL: 'Application name',
    DISPLAY_NAME_LABEL: 'Display name',
    DESCRIPTION_LABEL: 'Description',
    ERROR_GENERIC: 'Could not save changes. Please try again.',
  },
  FALLBACKS: {
    UNKNOWN: 'unknown',
    EMPTY: '—',
    NOT_ENRICHED: 'Not enriched.',
  },
  SECTIONS: {
    OVERVIEW: {
      TITLE: 'Application summary',
      DESCRIPTION: 'Core application metadata, health, history, and runtime configuration.',
      COMBINED_SUBTITLE: 'Core metadata, history, and runtime configuration.',
      COLUMN_PRIMARY: 'Status & metadata',
      COLUMN_RUNTIME: 'Runtime',
      REPLICAS: 'Replicas',
      DEPLOYED_IN: 'Deployed in',
      GROUP_HISTORY_META: 'History and drift',
      MANAGED_CHART: 'Managed chart',
      MANAGED_VERSION: 'Managed version',
      HISTORY_GENERATION: 'History generation',
      HAS_DRIFT: 'Has drift',
      LAST_MODIFIED_BY: 'Last modified by',
      LAST_MODIFIED_AT: 'Last modified at',
    },
    RESOURCE_SUMMARY: {
      TITLE: 'Resource summary',
      DESCRIPTION: 'Resource kind counts detected for this application.',
      EMPTY: 'No resources attached.',
    },
    NAMESPACES: {
      TITLE: 'Namespaces',
      DESCRIPTION: 'Namespaces associated with this application.',
    },
    DETAILS_TOOLBAR: {
      MORE_LABEL: 'More',
      MORE_TOOLTIP: 'More actions',
      SYNCED_PREFIX: 'synced',
      NEVER_SYNCED: 'never synced',
      SEPARATOR: '·',
    },
    RESOURCES: {
      TITLE: 'Resources',
      DESCRIPTION: 'Resources discovered for this application.',
      SHOWING_FIRST: 'Showing first',
      VIEW_GRAPH: 'Graph',
      VIEW_TREE: 'Tree',
      VIEW_GRAPH_TOOLTIP: 'Radial view',
      VIEW_TREE_TOOLTIP: 'Structure view',
    },
    INSIGHTS: {
      TITLE: 'Insights',
      DESCRIPTION: 'Enrichment results and suggestions (if available).',
      EMPTY_TITLE: 'No insights available',
      EMPTY_DESCRIPTION: 'No insights are available for this application yet.',
      ENRICHMENT_HINT:
        'Enrichment adds category, role, stack context, and suggestions when data is available from the platform.',
      CONFIDENCE: 'Confidence',
      CATEGORY: 'Category',
      ROLE: 'Role',
      ENRICHED_AT: 'Enriched at',
      DEPENDENCIES: 'Dependencies',
      RISKS: 'Risks',
      SUGGESTIONS: 'Suggestions',
      RELATED_APPS: 'Related apps',
      PROMPT_VERSION: 'Prompt version',
    },
    RUNTIME: {
      TITLE: 'Runtime',
      DESCRIPTION: 'Ports, images, and environment variable keys.',
      PORTS: 'Ports',
      IMAGES: 'Images',
      ENV_VAR_KEYS: 'Environment variables',
    },
    SNAPSHOTS: {
      TITLE: 'Snapshots',
      DESCRIPTION: 'Stored snapshots detected for this application.',
      SHOWING_FIRST: 'Showing first',
      EMPTY_TITLE: 'No snapshots yet',
      EMPTY_DESCRIPTION: 'No snapshots have been taken yet for this application.',
      ROLLBACKS_EMPTY_TITLE: 'No rollbacks yet',
      ROLLBACKS_EMPTY_DESCRIPTION: 'No rollbacks have been triggered yet for this application.',
      GENERATION: 'Generation',
      SEVERITY: 'Severity',
      SIZE: 'Size',
      RESTORED_PREFIX: 'Restored',
      // "Generation N" alone reads as the rollback's own generation. This says
      // which snapshot it went back to.
      ROLLBACK_TARGET_PREFIX: 'Rolled back to generation',
      BY_PREFIX: 'by',
      TRIGGERED_PREFIX: 'Triggered',
      COMPLETED_PREFIX: 'Completed',
      META_SEPARATOR: '·',
      SHOW_ERROR: 'Why did this fail?',
      HIDE_ERROR: 'Hide details',
      STORAGE_AVAILABLE: 'Available',
      STORAGE_TOTAL: 'Total',
      STORAGE_METRICS_JOINER: ' · ',
      COMPARE_LOADING: 'Loading manifest…',
      COMPARE_IDENTICAL: 'These two snapshots are identical.',
      COMPARE_CHANGE: 'change',
      COMPARE_RESOURCE: 'resource',
      VIEW_MANIFEST: 'View Manifest',
      ROLLBACK: 'Rollback',
      ROLLBACK_CONFIRM_TITLE: 'Rollback to this snapshot?',
      ROLLBACK_CONFIRM_CONTENT:
        'This starts a rollback to the selected snapshot. The application may be updated when the operation completes.',
      ROLLBACK_CONFIRM_OK: 'Start rollback',
      ROLLBACK_SUCCESS: 'Rollback request submitted.',
      ROLLBACK_FAILED: 'Rollback could not be started. Please try again.',
      ROLLBACK_USER_REQUIRED:
        'Sign in with a user account to start a rollback (username is required for the request).',
      TAKEN_AT: 'Taken at',
      MANIFEST_MODAL_TITLE: 'Manifest',
      MANIFEST_PANEL_SUBTITLE: 'Snapshot manifest',
      MANIFEST_BACK: 'Snapshots',
      MANIFEST_BACK_TOOLTIP: 'Back to snapshots',
      MANIFEST_TAB_JSON: 'JSON',
      MANIFEST_TAB_YAML: 'YAML',
      MANIFEST_COPY_TOOLTIP: 'Copy to clipboard',
      MANIFEST_COPIED: 'Copied',
      MANIFEST_COPY_FAILED: 'Failed to copy',
      MANIFEST_LOADING: 'Loading manifest…',
      MANIFEST_NOT_FOUND_TITLE: 'Manifest not available',
      MANIFEST_NOT_FOUND_DESCRIPTION:
        'No stored manifest was found for this snapshot. It may have been pruned by snapshot retention, or never captured.',
      MANIFEST_ERROR_TITLE: 'Could not load the manifest',
      MANIFEST_ERROR_DESCRIPTION: 'The manifest could not be read. Try again in a moment.',
      MANIFEST_EMPTY_TITLE: 'Nothing to show',
      MANIFEST_EMPTY_DESCRIPTION: 'This snapshot has an empty manifest.',
      MANIFEST_SHOW_DETAILS: 'Technical details',
      MANIFEST_HIDE_DETAILS: 'Hide details',
      VIEW_MANIFEST_PERMISSION_DENIED_TOOLTIP:
        'You do not have permission to view snapshot manifests',
      ROLLBACK_FILE_MISSING_TOOLTIP:
        'The stored snapshot for this entry is no longer available, so it cannot be rolled back to.',
      VIEW_MANIFEST_FILE_MISSING_TOOLTIP:
        'The stored snapshot for this entry is no longer available, so its manifest cannot be shown.',
      ROLLBACK_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to roll back applications',
      ROLLBACK_IN_PROGRESS_TOOLTIP:
        'Action unavailable while a rollback is pending or in progress for this application.',
      ABORT_ROLLBACK: 'Abort rollback',
      ABORT_ROLLBACK_TOOLTIP: 'Abort this pending rollback',
      ABORT_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to abort rollbacks',
      ABORT_CONFIRM_TITLE: 'Abort rollback?',
      ABORT_CONFIRM_CONTENT:
        'This rollback has not started yet. Aborting will cancel it permanently. Continue?',
      ABORT_CONFIRM_OK: 'Abort rollback',
      ABORT_SUCCESS: 'Rollback aborted.',
      ABORT_FAILED: 'Could not abort rollback. Please try again.',
      ABORT_USER_REQUIRED:
        'Sign in with a user account to abort a rollback (username is required for the request).',
    },
    METRICS: {
      TITLE: 'Metrics',
      DESCRIPTION: 'Derived change metrics for this application.',
      TIMELINE: 'Timeline',
      TOTAL_CHANGES: 'Total changes',
      SNAPSHOT_COUNT: 'Snapshot count',
      UNIQUE_FINGERPRINTS: 'Unique fingerprints',
      CHANGE_VELOCITY: 'Change velocity/day',
      FIRST_CHANGE: 'First change detected',
      LAST_CHANGE: 'Last change detected',
      TOTAL_INCIDENTS: 'Total incidents',
      TOTAL_RECOVERIES: 'Total recoveries',
      CHANGES_BY_CLASS: 'Changes by class',
      CHANGES_BY_SEVERITY: 'Changes by severity',
    },
    WORKLOAD_METRICS: {
      TITLE: 'Workload metrics',
      DESCRIPTION: 'Per-workload baseline and usage (when available).',
      USAGE_EMPTY: 'Usage data is not available for this workload yet.',
      OF_REQUEST: 'of request',
      OF_LIMIT: 'of limit',
      NO_BASELINE: 'no request set',
      REPLICAS_SUFFIX: 'replicas',
      INSTANCES_TITLE: 'Pods',
      POD_LABEL: 'Pod',
      CONTAINERS_LABEL: 'Containers running in this pod',
      POD_TOTAL_LABEL: 'pod total',
      POD_TOTAL_TOOLTIP: 'Sum of every container running in this pod.',
      LIMIT_TICK_TOOLTIP: 'Limit',
      SHOWING_FIRST_INSTANCES: 'Showing first 3 pods of',
      CPU_ABBREV: 'CPU',
      MEMORY_ABBREV: 'Mem',
      MID_DOT: '·',
      MORE_CONTAINERS_SUFFIX: 'more containers',
      RESOURCE_CPU_LABEL: 'CPU',
      RESOURCE_MEMORY_LABEL: 'Memory',
    },
    CHANGE_LOG: {
      TITLE: 'History Changes',
      DESCRIPTION: 'Detected changes and incidents.',
      SHOWING_FIRST: 'Showing first',
      GEN: 'Generation',
      BY_PREFIX: 'By',
      // The API appends the target snapshot id to the rollback description
      // ("... generation 1 snapshot snap-3415eeaa"). The id is already the
      // change's newValue and adds nothing to the sentence.
      ROLLBACK_SNAPSHOT_JOINER: ' snapshot ',
      DIFF_ARROW: '→',
      EMPTY_TITLE: 'No history yet',
      EMPTY_DESCRIPTION: 'No history recorded for this application yet.',
    },
  },
  CARD: {
    LABELS: {
      NAME: 'Name',
      NAMESPACE: 'Namespace',
      STATUS: 'Status',
      HEALTH: 'Health',
      NAMESPACES: 'Namespaces',
      RESOURCES: 'Resources',
      WORKLOADS: 'Workloads',
      MANAGED_BY: 'Managed by',
      LAST_UPDATED: 'Last updated',
      CREATED_AT: 'Created at',
      CR_STATUS: 'CR status',
      RUNTIME: 'Runtime',
      FOOTER_NAMESPACE: 'Namespace',
      FOOTER_MANAGED: 'Managed by',
      RUNTIME_CHIPS: {
        PORTS: 'ports',
        IMAGES: 'images',
        ENV_KEYS: 'env keys',
      },
    },
    ACTIONS: {
      VIEW: 'View',
      EDIT: 'Edit',
      FORCE_SYNC: 'Force Sync',
      MANAGE_SNAPSHOTS: 'Manage Snapshots',
      MANAGE_ROLLBACKS: 'Manage Rollbacks',
      SYNC_DISABLED_TOOLTIP: 'Action is unavailable while sync is in progress.',
      EDIT_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to edit applications',
      FORCE_SYNC_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to sync applications',
      VIEW_SNAPSHOTS_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to view snapshots',
      VIEW_ROLLBACKS_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to view rollbacks',
      DELETE_PERMISSION_DENIED_TOOLTIP: 'You do not have permission to delete applications',
      CANCEL: 'Cancel',
      DELETE: 'Delete',
      DELETE_CONFIRM_TITLE: 'Delete application?',
      DELETE_CONFIRM_CONTENT: 'This action cannot be undone.',
      DELETE_CONFIRM_MESSAGE:
        'Deleting this application removes only its definition from the platform. Kubernetes resources in your cluster are not deleted.',
      ROLLBACKS_PLACEHOLDER: 'Rollbacks are managed from the snapshots section.',
    },
    SYNC_STATUS: {
      SYNCING: 'Syncing',
      SUCCESS: 'Synced',
      FAILED: 'Sync failed',
    },
  },
} as const;
