export const INSIGHTS_GOVERNANCE_CONSTANTS = {
  LABELS: {
    AI_INSIGHTS_TITLE: 'Insights',
    AI_INSIGHTS_DESCRIPTION:
      'By default, rules find each incident and setup issue and a model running in this cluster only rewrites the summary. Deep mode lets the model investigate with the same read-only tools. No data leaves the cluster.',
    EXPERIMENTAL_BADGE: 'Experimental',
    ENABLE_AI_LABEL: 'Enable Insights',
    AUTO_ANALYZE_LABEL: 'Analyze automatically on incidents and recoveries',
    MODEL_LABEL: 'Model',
    MODEL_HINT: 'A change applies from the next run.',
    MODEL_HINT_DEEP: 'Deep mode: the model must support tool calling.',
    MODE_LABELS: {
      fast: 'Fast (rules + short narration)',
      deep: 'Deep (multi-step investigation)',
    },
    AIR_GAPPED_HINT:
      'Model downloads are disabled for this release (air-gapped). Load the model on the runtime volume, then pick it here.',
    RUNTIME_MODE_TITLE: 'Mode',
    INSTALL_MODEL_BUTTON: 'Install model',
    VALIDATE_BUTTON: 'Check model',
    RUNTIME_STATUS_TITLE: 'Runtime',
    RUNTIME_STATE_LABELS: {
      absent: 'Not installed',
      unreachable: 'Unreachable',
      model_missing: 'Model not installed',
      pulling: 'Installing model…',
      unsupported: 'Model does not support tools',
      ready: 'Ready',
    },
    HELM_HINT_TEXT: 'Enable the model runtime in your release:',
    HELM_HINT_COMMAND:
      'helm upgrade telark oci://ghcr.io/telark/charts/telark -n telark --reset-then-reuse-values --set app.ollama.enabled=true',
    LICENSE_WARNING: 'This model is licensed for research use only.',
    COPY_BUTTON: 'Copy',
    SAVE_BUTTON: 'Save',
    SAVE_TITLE: 'Save',
    SAVE_DESCRIPTION: 'Apply changes to the cluster-wide GlobalConfig.',
    ENABLE_BUTTON: 'Enable',
    NAMESPACES_TITLE: 'Excluded namespaces',
    NAMESPACES_DESCRIPTION:
      'Choose namespaces to exclude from discovery and platform insights. System namespaces are pre-selected by default.',
    NAMESPACES_SELECTOR_PLACEHOLDER: 'Select namespaces…',
    NAMESPACES_IMPACT_NOUN: 'application',
    NAMESPACES_IMPACT_HIDDEN: 'will be hidden',
    NAMESPACES_IMPACT_REVEALED: 'will be revealed',
    NAMESPACES_SAVE_BUTTON: 'Save namespaces',
    PLATFORM_TITLE: 'Platform behavior',
    PLATFORM_DESCRIPTION: 'Polling and snapshot retention settings.',
    FETCH_INTERVAL_MINUTES_LABEL: 'Fetch interval (minutes)',
    FETCH_INTERVAL_MINUTE_NOUN: 'minute',
    FETCH_INTERVAL_ONE_HOUR: '1 hour',
    CUSTOM_OPTION: 'Custom',
    SNAPSHOTS_MAX_PER_APP_LABEL: 'Maximum Snapshots per application',
    SNAPSHOTS_MAX_PER_APP_HINT:
      'Telark saves a snapshot before each change and keeps the most recent ones, up to this number. Older snapshots are deleted. Their changes stay in the history, but you can no longer compare them or roll back to them. For applications in several namespaces, the limit applies per namespace. A new limit takes effect from the next change.',
    PLATFORM_SAVE_INTERVAL_BUTTON: 'Save interval',
    PLATFORM_SAVE_SNAPSHOTS_BUTTON: 'Save snapshots',
    EDIT_DISCOVERY_CONFIG_PERMISSION_DENIED:
      'You do not have permission to edit discovery & behavior settings',
    EDIT_SNAPSHOT_STORAGE_PERMISSION_DENIED:
      'You do not have permission to edit snapshot storage settings',
    CONTROL_AI_INSIGHTS_PERMISSION_DENIED: 'You do not have permission to manage Insights settings',
    SNAPSHOT_STORAGE_TITLE: 'Snapshot Storage',
    SNAPSHOT_STORAGE_DESCRIPTION: 'Storage usage and retention controls for snapshots.',
    SNAPSHOT_STORAGE_LOADING: 'Loading snapshot storage...',
    SNAPSHOT_STORAGE_NO_ACCESS: 'You do not have permission to view snapshot storage usage',
    SNAPSHOT_STORAGE_CONSUMED: 'Consumed',
    SNAPSHOT_STORAGE_AVAILABLE: 'Available',
    SNAPSHOT_STORAGE_USAGE_LABEL: 'Usage',
    SNAPSHOT_STORAGE_TOTAL_SNAPSHOTS: 'Total snapshots',
  },
  MESSAGES: {
    MODEL_VALID: 'Model is ready.',
    MODEL_LACKS_TOOLS: 'This model cannot use tools; pick another.',
    PULL_STARTED: 'Model installation started.',
    PULL_FAILED: 'Failed to start the model installation.',
    MODEL_NOT_INSTALLED: 'This model is not installed yet; use Install model.',
    INVALID_MODEL_NAME: 'Enter a model tag such as granite4:350m.',
    CHECK_FAILED: 'Could not check the model.',
    COPIED: 'Command copied.',
    COPY_FAILED: 'Could not copy the command.',
    SAVE_SUCCESS: 'Settings saved.',
    SAVE_FAILED: 'Failed to save settings.',
    NAMESPACES_LOAD_FAILED: 'Failed to load namespaces.',
    NAMESPACES_SAVE_SUCCESS: 'Namespaces saved.',
    NAMESPACES_SAVE_FAILED: 'Failed to save namespaces.',
    PLATFORM_SAVE_INTERVAL_SUCCESS: 'Interval saved.',
    PLATFORM_SAVE_INTERVAL_FAILED: 'Failed to save interval.',
    PLATFORM_SAVE_SNAPSHOTS_SUCCESS: 'Snapshots saved.',
    PLATFORM_SAVE_SNAPSHOTS_FAILED: 'Failed to save snapshots.',
    SNAPSHOT_STORAGE_LOAD_FAILED: 'Failed to load snapshot storage.',
  },
  MODELS: {
    DEFAULT: 'granite4:350m',
    NAME_PATTERN: /^[a-z0-9][a-z0-9._-]*(:[a-z0-9._-]+)?$/,
    OPTIONS: [
      { value: 'granite4:350m', license: 'Apache-2.0', research: false },
      { value: 'qwen3:1.7b', license: 'Apache-2.0', research: false },
      { value: 'qwen3:4b', license: 'Apache-2.0', research: false },
      { value: 'qwen2.5:7b', license: 'Apache-2.0', research: false },
    ],
  },
  LAYOUT: {
    FIELD_COLUMN_GAP: 10,
    FIELD_ROW_GAP: 12,
  },
} as const;
