import { DEFAULT_COLORS } from '../../../constants';

export const TABLE_DEFAULTS = {
  HEADER_BG: '#fff',
  HEADER_ICON_GAP: 6,
  SORT_ICON_SIZE: 14,
  ICON_MUTED: DEFAULT_COLORS.TEXT_ON_SURFACE_MUTED,
  SORT_ACTIVE: DEFAULT_COLORS.SUCCESS,
  SORT_INACTIVE: DEFAULT_COLORS.TEXT_ON_SURFACE_DISABLED,
  HEADER_ALIGN_DEFAULT: 'center' as const,
  SELECT_COLUMN_WIDTH: 48,
  SCROLL_X: 1200,
} as const;
